// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BaseResp.proto

package com.pureland.common.protocal;

public final class BaseRespProtocal {
  private BaseRespProtocal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BaseRespOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .BaseResp.ErrorType errorType = 1;
    /**
     * <code>required .BaseResp.ErrorType errorType = 1;</code>
     */
    boolean hasErrorType();
    /**
     * <code>required .BaseResp.ErrorType errorType = 1;</code>
     */
    com.pureland.common.protocal.BaseRespProtocal.BaseResp.ErrorType getErrorType();

    // optional .RespWrapper respWrapper = 2;
    /**
     * <code>optional .RespWrapper respWrapper = 2;</code>
     */
    boolean hasRespWrapper();
    /**
     * <code>optional .RespWrapper respWrapper = 2;</code>
     */
    com.pureland.common.protocal.RespWrapperProtocal.RespWrapper getRespWrapper();
    /**
     * <code>optional .RespWrapper respWrapper = 2;</code>
     */
    com.pureland.common.protocal.RespWrapperProtocal.RespWrapperOrBuilder getRespWrapperOrBuilder();

    // optional string errorMessage = 3;
    /**
     * <code>optional string errorMessage = 3;</code>
     */
    boolean hasErrorMessage();
    /**
     * <code>optional string errorMessage = 3;</code>
     */
    java.lang.String getErrorMessage();
    /**
     * <code>optional string errorMessage = 3;</code>
     */
    com.google.protobuf.ByteString
        getErrorMessageBytes();
  }
  /**
   * Protobuf type {@code BaseResp}
   */
  public static final class BaseResp extends
      com.google.protobuf.GeneratedMessage
      implements BaseRespOrBuilder {
    // Use BaseResp.newBuilder() to construct.
    private BaseResp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BaseResp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BaseResp defaultInstance;
    public static BaseResp getDefaultInstance() {
      return defaultInstance;
    }

    public BaseResp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BaseResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.pureland.common.protocal.BaseRespProtocal.BaseResp.ErrorType value = com.pureland.common.protocal.BaseRespProtocal.BaseResp.ErrorType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                errorType_ = value;
              }
              break;
            }
            case 18: {
              com.pureland.common.protocal.RespWrapperProtocal.RespWrapper.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = respWrapper_.toBuilder();
              }
              respWrapper_ = input.readMessage(com.pureland.common.protocal.RespWrapperProtocal.RespWrapper.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(respWrapper_);
                respWrapper_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              errorMessage_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pureland.common.protocal.BaseRespProtocal.internal_static_BaseResp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pureland.common.protocal.BaseRespProtocal.internal_static_BaseResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pureland.common.protocal.BaseRespProtocal.BaseResp.class, com.pureland.common.protocal.BaseRespProtocal.BaseResp.Builder.class);
    }

    public static com.google.protobuf.Parser<BaseResp> PARSER =
        new com.google.protobuf.AbstractParser<BaseResp>() {
      public BaseResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BaseResp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BaseResp> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code BaseResp.ErrorType}
     */
    public enum ErrorType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>OK = 0;</code>
       *
       * <pre>
       *无错误
       * </pre>
       */
      OK(0, 0),
      /**
       * <code>AuthFailed = 1;</code>
       *
       * <pre>
       *身份认证失败
       * </pre>
       */
      AuthFailed(1, 1),
      /**
       * <code>DataVerifyFailed = 2;</code>
       *
       * <pre>
       *数据验证失败
       * </pre>
       */
      DataVerifyFailed(2, 2),
      /**
       * <code>IsInFight = 3;</code>
       *
       * <pre>
       *是否在战斗
       * </pre>
       */
      IsInFight(3, 3),
      /**
       * <code>IsOffLine = 4;</code>
       *
       * <pre>
       *是否离线
       * </pre>
       */
      IsOffLine(4, 4),
      ;

      /**
       * <code>OK = 0;</code>
       *
       * <pre>
       *无错误
       * </pre>
       */
      public static final int OK_VALUE = 0;
      /**
       * <code>AuthFailed = 1;</code>
       *
       * <pre>
       *身份认证失败
       * </pre>
       */
      public static final int AuthFailed_VALUE = 1;
      /**
       * <code>DataVerifyFailed = 2;</code>
       *
       * <pre>
       *数据验证失败
       * </pre>
       */
      public static final int DataVerifyFailed_VALUE = 2;
      /**
       * <code>IsInFight = 3;</code>
       *
       * <pre>
       *是否在战斗
       * </pre>
       */
      public static final int IsInFight_VALUE = 3;
      /**
       * <code>IsOffLine = 4;</code>
       *
       * <pre>
       *是否离线
       * </pre>
       */
      public static final int IsOffLine_VALUE = 4;


      public final int getNumber() { return value; }

      public static ErrorType valueOf(int value) {
        switch (value) {
          case 0: return OK;
          case 1: return AuthFailed;
          case 2: return DataVerifyFailed;
          case 3: return IsInFight;
          case 4: return IsOffLine;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ErrorType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ErrorType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ErrorType>() {
              public ErrorType findValueByNumber(int number) {
                return ErrorType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.pureland.common.protocal.BaseRespProtocal.BaseResp.getDescriptor().getEnumTypes().get(0);
      }

      private static final ErrorType[] VALUES = values();

      public static ErrorType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ErrorType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:BaseResp.ErrorType)
    }

    private int bitField0_;
    // required .BaseResp.ErrorType errorType = 1;
    public static final int ERRORTYPE_FIELD_NUMBER = 1;
    private com.pureland.common.protocal.BaseRespProtocal.BaseResp.ErrorType errorType_;
    /**
     * <code>required .BaseResp.ErrorType errorType = 1;</code>
     */
    public boolean hasErrorType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .BaseResp.ErrorType errorType = 1;</code>
     */
    public com.pureland.common.protocal.BaseRespProtocal.BaseResp.ErrorType getErrorType() {
      return errorType_;
    }

    // optional .RespWrapper respWrapper = 2;
    public static final int RESPWRAPPER_FIELD_NUMBER = 2;
    private com.pureland.common.protocal.RespWrapperProtocal.RespWrapper respWrapper_;
    /**
     * <code>optional .RespWrapper respWrapper = 2;</code>
     */
    public boolean hasRespWrapper() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .RespWrapper respWrapper = 2;</code>
     */
    public com.pureland.common.protocal.RespWrapperProtocal.RespWrapper getRespWrapper() {
      return respWrapper_;
    }
    /**
     * <code>optional .RespWrapper respWrapper = 2;</code>
     */
    public com.pureland.common.protocal.RespWrapperProtocal.RespWrapperOrBuilder getRespWrapperOrBuilder() {
      return respWrapper_;
    }

    // optional string errorMessage = 3;
    public static final int ERRORMESSAGE_FIELD_NUMBER = 3;
    private java.lang.Object errorMessage_;
    /**
     * <code>optional string errorMessage = 3;</code>
     */
    public boolean hasErrorMessage() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string errorMessage = 3;</code>
     */
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errorMessage_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string errorMessage = 3;</code>
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      errorType_ = com.pureland.common.protocal.BaseRespProtocal.BaseResp.ErrorType.OK;
      respWrapper_ = com.pureland.common.protocal.RespWrapperProtocal.RespWrapper.getDefaultInstance();
      errorMessage_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasErrorType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasRespWrapper()) {
        if (!getRespWrapper().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, errorType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, respWrapper_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getErrorMessageBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, errorType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, respWrapper_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getErrorMessageBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.pureland.common.protocal.BaseRespProtocal.BaseResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pureland.common.protocal.BaseRespProtocal.BaseResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pureland.common.protocal.BaseRespProtocal.BaseResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pureland.common.protocal.BaseRespProtocal.BaseResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pureland.common.protocal.BaseRespProtocal.BaseResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.pureland.common.protocal.BaseRespProtocal.BaseResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.pureland.common.protocal.BaseRespProtocal.BaseResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.pureland.common.protocal.BaseRespProtocal.BaseResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.pureland.common.protocal.BaseRespProtocal.BaseResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.pureland.common.protocal.BaseRespProtocal.BaseResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.pureland.common.protocal.BaseRespProtocal.BaseResp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BaseResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.pureland.common.protocal.BaseRespProtocal.BaseRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pureland.common.protocal.BaseRespProtocal.internal_static_BaseResp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pureland.common.protocal.BaseRespProtocal.internal_static_BaseResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pureland.common.protocal.BaseRespProtocal.BaseResp.class, com.pureland.common.protocal.BaseRespProtocal.BaseResp.Builder.class);
      }

      // Construct using com.pureland.common.protocal.BaseRespProtocal.BaseResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRespWrapperFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        errorType_ = com.pureland.common.protocal.BaseRespProtocal.BaseResp.ErrorType.OK;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (respWrapperBuilder_ == null) {
          respWrapper_ = com.pureland.common.protocal.RespWrapperProtocal.RespWrapper.getDefaultInstance();
        } else {
          respWrapperBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        errorMessage_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pureland.common.protocal.BaseRespProtocal.internal_static_BaseResp_descriptor;
      }

      public com.pureland.common.protocal.BaseRespProtocal.BaseResp getDefaultInstanceForType() {
        return com.pureland.common.protocal.BaseRespProtocal.BaseResp.getDefaultInstance();
      }

      public com.pureland.common.protocal.BaseRespProtocal.BaseResp build() {
        com.pureland.common.protocal.BaseRespProtocal.BaseResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.pureland.common.protocal.BaseRespProtocal.BaseResp buildPartial() {
        com.pureland.common.protocal.BaseRespProtocal.BaseResp result = new com.pureland.common.protocal.BaseRespProtocal.BaseResp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.errorType_ = errorType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (respWrapperBuilder_ == null) {
          result.respWrapper_ = respWrapper_;
        } else {
          result.respWrapper_ = respWrapperBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.errorMessage_ = errorMessage_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pureland.common.protocal.BaseRespProtocal.BaseResp) {
          return mergeFrom((com.pureland.common.protocal.BaseRespProtocal.BaseResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.pureland.common.protocal.BaseRespProtocal.BaseResp other) {
        if (other == com.pureland.common.protocal.BaseRespProtocal.BaseResp.getDefaultInstance()) return this;
        if (other.hasErrorType()) {
          setErrorType(other.getErrorType());
        }
        if (other.hasRespWrapper()) {
          mergeRespWrapper(other.getRespWrapper());
        }
        if (other.hasErrorMessage()) {
          bitField0_ |= 0x00000004;
          errorMessage_ = other.errorMessage_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasErrorType()) {
          
          return false;
        }
        if (hasRespWrapper()) {
          if (!getRespWrapper().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.pureland.common.protocal.BaseRespProtocal.BaseResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.pureland.common.protocal.BaseRespProtocal.BaseResp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .BaseResp.ErrorType errorType = 1;
      private com.pureland.common.protocal.BaseRespProtocal.BaseResp.ErrorType errorType_ = com.pureland.common.protocal.BaseRespProtocal.BaseResp.ErrorType.OK;
      /**
       * <code>required .BaseResp.ErrorType errorType = 1;</code>
       */
      public boolean hasErrorType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .BaseResp.ErrorType errorType = 1;</code>
       */
      public com.pureland.common.protocal.BaseRespProtocal.BaseResp.ErrorType getErrorType() {
        return errorType_;
      }
      /**
       * <code>required .BaseResp.ErrorType errorType = 1;</code>
       */
      public Builder setErrorType(com.pureland.common.protocal.BaseRespProtocal.BaseResp.ErrorType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        errorType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .BaseResp.ErrorType errorType = 1;</code>
       */
      public Builder clearErrorType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        errorType_ = com.pureland.common.protocal.BaseRespProtocal.BaseResp.ErrorType.OK;
        onChanged();
        return this;
      }

      // optional .RespWrapper respWrapper = 2;
      private com.pureland.common.protocal.RespWrapperProtocal.RespWrapper respWrapper_ = com.pureland.common.protocal.RespWrapperProtocal.RespWrapper.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.pureland.common.protocal.RespWrapperProtocal.RespWrapper, com.pureland.common.protocal.RespWrapperProtocal.RespWrapper.Builder, com.pureland.common.protocal.RespWrapperProtocal.RespWrapperOrBuilder> respWrapperBuilder_;
      /**
       * <code>optional .RespWrapper respWrapper = 2;</code>
       */
      public boolean hasRespWrapper() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .RespWrapper respWrapper = 2;</code>
       */
      public com.pureland.common.protocal.RespWrapperProtocal.RespWrapper getRespWrapper() {
        if (respWrapperBuilder_ == null) {
          return respWrapper_;
        } else {
          return respWrapperBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .RespWrapper respWrapper = 2;</code>
       */
      public Builder setRespWrapper(com.pureland.common.protocal.RespWrapperProtocal.RespWrapper value) {
        if (respWrapperBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          respWrapper_ = value;
          onChanged();
        } else {
          respWrapperBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .RespWrapper respWrapper = 2;</code>
       */
      public Builder setRespWrapper(
          com.pureland.common.protocal.RespWrapperProtocal.RespWrapper.Builder builderForValue) {
        if (respWrapperBuilder_ == null) {
          respWrapper_ = builderForValue.build();
          onChanged();
        } else {
          respWrapperBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .RespWrapper respWrapper = 2;</code>
       */
      public Builder mergeRespWrapper(com.pureland.common.protocal.RespWrapperProtocal.RespWrapper value) {
        if (respWrapperBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              respWrapper_ != com.pureland.common.protocal.RespWrapperProtocal.RespWrapper.getDefaultInstance()) {
            respWrapper_ =
              com.pureland.common.protocal.RespWrapperProtocal.RespWrapper.newBuilder(respWrapper_).mergeFrom(value).buildPartial();
          } else {
            respWrapper_ = value;
          }
          onChanged();
        } else {
          respWrapperBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .RespWrapper respWrapper = 2;</code>
       */
      public Builder clearRespWrapper() {
        if (respWrapperBuilder_ == null) {
          respWrapper_ = com.pureland.common.protocal.RespWrapperProtocal.RespWrapper.getDefaultInstance();
          onChanged();
        } else {
          respWrapperBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .RespWrapper respWrapper = 2;</code>
       */
      public com.pureland.common.protocal.RespWrapperProtocal.RespWrapper.Builder getRespWrapperBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getRespWrapperFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .RespWrapper respWrapper = 2;</code>
       */
      public com.pureland.common.protocal.RespWrapperProtocal.RespWrapperOrBuilder getRespWrapperOrBuilder() {
        if (respWrapperBuilder_ != null) {
          return respWrapperBuilder_.getMessageOrBuilder();
        } else {
          return respWrapper_;
        }
      }
      /**
       * <code>optional .RespWrapper respWrapper = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.pureland.common.protocal.RespWrapperProtocal.RespWrapper, com.pureland.common.protocal.RespWrapperProtocal.RespWrapper.Builder, com.pureland.common.protocal.RespWrapperProtocal.RespWrapperOrBuilder> 
          getRespWrapperFieldBuilder() {
        if (respWrapperBuilder_ == null) {
          respWrapperBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.pureland.common.protocal.RespWrapperProtocal.RespWrapper, com.pureland.common.protocal.RespWrapperProtocal.RespWrapper.Builder, com.pureland.common.protocal.RespWrapperProtocal.RespWrapperOrBuilder>(
                  respWrapper_,
                  getParentForChildren(),
                  isClean());
          respWrapper_ = null;
        }
        return respWrapperBuilder_;
      }

      // optional string errorMessage = 3;
      private java.lang.Object errorMessage_ = "";
      /**
       * <code>optional string errorMessage = 3;</code>
       */
      public boolean hasErrorMessage() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string errorMessage = 3;</code>
       */
      public java.lang.String getErrorMessage() {
        java.lang.Object ref = errorMessage_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          errorMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string errorMessage = 3;</code>
       */
      public com.google.protobuf.ByteString
          getErrorMessageBytes() {
        java.lang.Object ref = errorMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string errorMessage = 3;</code>
       */
      public Builder setErrorMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        errorMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorMessage = 3;</code>
       */
      public Builder clearErrorMessage() {
        bitField0_ = (bitField0_ & ~0x00000004);
        errorMessage_ = getDefaultInstance().getErrorMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorMessage = 3;</code>
       */
      public Builder setErrorMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        errorMessage_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BaseResp)
    }

    static {
      defaultInstance = new BaseResp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BaseResp)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BaseResp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BaseResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016BaseResp.proto\032\021RespWrapper.proto\"\304\001\n\010" +
      "BaseResp\022&\n\terrorType\030\001 \002(\0162\023.BaseResp.E" +
      "rrorType\022!\n\013respWrapper\030\002 \001(\0132\014.RespWrap" +
      "per\022\024\n\014errorMessage\030\003 \001(\t\"W\n\tErrorType\022\006" +
      "\n\002OK\020\000\022\016\n\nAuthFailed\020\001\022\024\n\020DataVerifyFail" +
      "ed\020\002\022\r\n\tIsInFight\020\003\022\r\n\tIsOffLine\020\004B0\n\034co" +
      "m.pureland.common.protocalB\020BaseRespProt" +
      "ocal"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_BaseResp_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_BaseResp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BaseResp_descriptor,
              new java.lang.String[] { "ErrorType", "RespWrapper", "ErrorMessage", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.pureland.common.protocal.RespWrapperProtocal.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
