// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BuildingUpgradeReq.proto

package com.pureland.common.protocal;

public final class BuildingUpgradeReqProtocal {
  private BuildingUpgradeReqProtocal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BuildingUpgradeReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 sid = 1;
    /**
     * <code>required int64 sid = 1;</code>
     */
    boolean hasSid();
    /**
     * <code>required int64 sid = 1;</code>
     */
    long getSid();

    // required .ResourceType resourceType = 2;
    /**
     * <code>required .ResourceType resourceType = 2;</code>
     */
    boolean hasResourceType();
    /**
     * <code>required .ResourceType resourceType = 2;</code>
     */
    com.pureland.common.protocal.vo.ResourceTypeProtocal.ResourceType getResourceType();

    // optional bool cancel = 3;
    /**
     * <code>optional bool cancel = 3;</code>
     */
    boolean hasCancel();
    /**
     * <code>optional bool cancel = 3;</code>
     */
    boolean getCancel();

    // optional int64 endTime = 4;
    /**
     * <code>optional int64 endTime = 4;</code>
     */
    boolean hasEndTime();
    /**
     * <code>optional int64 endTime = 4;</code>
     */
    long getEndTime();
  }
  /**
   * Protobuf type {@code BuildingUpgradeReq}
   */
  public static final class BuildingUpgradeReq extends
      com.google.protobuf.GeneratedMessage
      implements BuildingUpgradeReqOrBuilder {
    // Use BuildingUpgradeReq.newBuilder() to construct.
    private BuildingUpgradeReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BuildingUpgradeReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BuildingUpgradeReq defaultInstance;
    public static BuildingUpgradeReq getDefaultInstance() {
      return defaultInstance;
    }

    public BuildingUpgradeReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BuildingUpgradeReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              sid_ = input.readInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.pureland.common.protocal.vo.ResourceTypeProtocal.ResourceType value = com.pureland.common.protocal.vo.ResourceTypeProtocal.ResourceType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                resourceType_ = value;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              cancel_ = input.readBool();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              endTime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pureland.common.protocal.BuildingUpgradeReqProtocal.internal_static_BuildingUpgradeReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pureland.common.protocal.BuildingUpgradeReqProtocal.internal_static_BuildingUpgradeReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pureland.common.protocal.BuildingUpgradeReqProtocal.BuildingUpgradeReq.class, com.pureland.common.protocal.BuildingUpgradeReqProtocal.BuildingUpgradeReq.Builder.class);
    }

    public static com.google.protobuf.Parser<BuildingUpgradeReq> PARSER =
        new com.google.protobuf.AbstractParser<BuildingUpgradeReq>() {
      public BuildingUpgradeReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BuildingUpgradeReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BuildingUpgradeReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 sid = 1;
    public static final int SID_FIELD_NUMBER = 1;
    private long sid_;
    /**
     * <code>required int64 sid = 1;</code>
     */
    public boolean hasSid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 sid = 1;</code>
     */
    public long getSid() {
      return sid_;
    }

    // required .ResourceType resourceType = 2;
    public static final int RESOURCETYPE_FIELD_NUMBER = 2;
    private com.pureland.common.protocal.vo.ResourceTypeProtocal.ResourceType resourceType_;
    /**
     * <code>required .ResourceType resourceType = 2;</code>
     */
    public boolean hasResourceType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .ResourceType resourceType = 2;</code>
     */
    public com.pureland.common.protocal.vo.ResourceTypeProtocal.ResourceType getResourceType() {
      return resourceType_;
    }

    // optional bool cancel = 3;
    public static final int CANCEL_FIELD_NUMBER = 3;
    private boolean cancel_;
    /**
     * <code>optional bool cancel = 3;</code>
     */
    public boolean hasCancel() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bool cancel = 3;</code>
     */
    public boolean getCancel() {
      return cancel_;
    }

    // optional int64 endTime = 4;
    public static final int ENDTIME_FIELD_NUMBER = 4;
    private long endTime_;
    /**
     * <code>optional int64 endTime = 4;</code>
     */
    public boolean hasEndTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 endTime = 4;</code>
     */
    public long getEndTime() {
      return endTime_;
    }

    private void initFields() {
      sid_ = 0L;
      resourceType_ = com.pureland.common.protocal.vo.ResourceTypeProtocal.ResourceType.None;
      cancel_ = false;
      endTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasResourceType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, sid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, resourceType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, cancel_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, endTime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, sid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, resourceType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, cancel_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, endTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.pureland.common.protocal.BuildingUpgradeReqProtocal.BuildingUpgradeReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pureland.common.protocal.BuildingUpgradeReqProtocal.BuildingUpgradeReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pureland.common.protocal.BuildingUpgradeReqProtocal.BuildingUpgradeReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pureland.common.protocal.BuildingUpgradeReqProtocal.BuildingUpgradeReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pureland.common.protocal.BuildingUpgradeReqProtocal.BuildingUpgradeReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.pureland.common.protocal.BuildingUpgradeReqProtocal.BuildingUpgradeReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.pureland.common.protocal.BuildingUpgradeReqProtocal.BuildingUpgradeReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.pureland.common.protocal.BuildingUpgradeReqProtocal.BuildingUpgradeReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.pureland.common.protocal.BuildingUpgradeReqProtocal.BuildingUpgradeReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.pureland.common.protocal.BuildingUpgradeReqProtocal.BuildingUpgradeReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.pureland.common.protocal.BuildingUpgradeReqProtocal.BuildingUpgradeReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BuildingUpgradeReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.pureland.common.protocal.BuildingUpgradeReqProtocal.BuildingUpgradeReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pureland.common.protocal.BuildingUpgradeReqProtocal.internal_static_BuildingUpgradeReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pureland.common.protocal.BuildingUpgradeReqProtocal.internal_static_BuildingUpgradeReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pureland.common.protocal.BuildingUpgradeReqProtocal.BuildingUpgradeReq.class, com.pureland.common.protocal.BuildingUpgradeReqProtocal.BuildingUpgradeReq.Builder.class);
      }

      // Construct using com.pureland.common.protocal.BuildingUpgradeReqProtocal.BuildingUpgradeReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        resourceType_ = com.pureland.common.protocal.vo.ResourceTypeProtocal.ResourceType.None;
        bitField0_ = (bitField0_ & ~0x00000002);
        cancel_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        endTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pureland.common.protocal.BuildingUpgradeReqProtocal.internal_static_BuildingUpgradeReq_descriptor;
      }

      public com.pureland.common.protocal.BuildingUpgradeReqProtocal.BuildingUpgradeReq getDefaultInstanceForType() {
        return com.pureland.common.protocal.BuildingUpgradeReqProtocal.BuildingUpgradeReq.getDefaultInstance();
      }

      public com.pureland.common.protocal.BuildingUpgradeReqProtocal.BuildingUpgradeReq build() {
        com.pureland.common.protocal.BuildingUpgradeReqProtocal.BuildingUpgradeReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.pureland.common.protocal.BuildingUpgradeReqProtocal.BuildingUpgradeReq buildPartial() {
        com.pureland.common.protocal.BuildingUpgradeReqProtocal.BuildingUpgradeReq result = new com.pureland.common.protocal.BuildingUpgradeReqProtocal.BuildingUpgradeReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sid_ = sid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.resourceType_ = resourceType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.cancel_ = cancel_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.endTime_ = endTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pureland.common.protocal.BuildingUpgradeReqProtocal.BuildingUpgradeReq) {
          return mergeFrom((com.pureland.common.protocal.BuildingUpgradeReqProtocal.BuildingUpgradeReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.pureland.common.protocal.BuildingUpgradeReqProtocal.BuildingUpgradeReq other) {
        if (other == com.pureland.common.protocal.BuildingUpgradeReqProtocal.BuildingUpgradeReq.getDefaultInstance()) return this;
        if (other.hasSid()) {
          setSid(other.getSid());
        }
        if (other.hasResourceType()) {
          setResourceType(other.getResourceType());
        }
        if (other.hasCancel()) {
          setCancel(other.getCancel());
        }
        if (other.hasEndTime()) {
          setEndTime(other.getEndTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSid()) {
          
          return false;
        }
        if (!hasResourceType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.pureland.common.protocal.BuildingUpgradeReqProtocal.BuildingUpgradeReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.pureland.common.protocal.BuildingUpgradeReqProtocal.BuildingUpgradeReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 sid = 1;
      private long sid_ ;
      /**
       * <code>required int64 sid = 1;</code>
       */
      public boolean hasSid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 sid = 1;</code>
       */
      public long getSid() {
        return sid_;
      }
      /**
       * <code>required int64 sid = 1;</code>
       */
      public Builder setSid(long value) {
        bitField0_ |= 0x00000001;
        sid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 sid = 1;</code>
       */
      public Builder clearSid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sid_ = 0L;
        onChanged();
        return this;
      }

      // required .ResourceType resourceType = 2;
      private com.pureland.common.protocal.vo.ResourceTypeProtocal.ResourceType resourceType_ = com.pureland.common.protocal.vo.ResourceTypeProtocal.ResourceType.None;
      /**
       * <code>required .ResourceType resourceType = 2;</code>
       */
      public boolean hasResourceType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .ResourceType resourceType = 2;</code>
       */
      public com.pureland.common.protocal.vo.ResourceTypeProtocal.ResourceType getResourceType() {
        return resourceType_;
      }
      /**
       * <code>required .ResourceType resourceType = 2;</code>
       */
      public Builder setResourceType(com.pureland.common.protocal.vo.ResourceTypeProtocal.ResourceType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        resourceType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .ResourceType resourceType = 2;</code>
       */
      public Builder clearResourceType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        resourceType_ = com.pureland.common.protocal.vo.ResourceTypeProtocal.ResourceType.None;
        onChanged();
        return this;
      }

      // optional bool cancel = 3;
      private boolean cancel_ ;
      /**
       * <code>optional bool cancel = 3;</code>
       */
      public boolean hasCancel() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bool cancel = 3;</code>
       */
      public boolean getCancel() {
        return cancel_;
      }
      /**
       * <code>optional bool cancel = 3;</code>
       */
      public Builder setCancel(boolean value) {
        bitField0_ |= 0x00000004;
        cancel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool cancel = 3;</code>
       */
      public Builder clearCancel() {
        bitField0_ = (bitField0_ & ~0x00000004);
        cancel_ = false;
        onChanged();
        return this;
      }

      // optional int64 endTime = 4;
      private long endTime_ ;
      /**
       * <code>optional int64 endTime = 4;</code>
       */
      public boolean hasEndTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 endTime = 4;</code>
       */
      public long getEndTime() {
        return endTime_;
      }
      /**
       * <code>optional int64 endTime = 4;</code>
       */
      public Builder setEndTime(long value) {
        bitField0_ |= 0x00000008;
        endTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 endTime = 4;</code>
       */
      public Builder clearEndTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        endTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BuildingUpgradeReq)
    }

    static {
      defaultInstance = new BuildingUpgradeReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BuildingUpgradeReq)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BuildingUpgradeReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BuildingUpgradeReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030BuildingUpgradeReq.proto\032\022ResourceType" +
      ".proto\"g\n\022BuildingUpgradeReq\022\013\n\003sid\030\001 \002(" +
      "\003\022#\n\014resourceType\030\002 \002(\0162\r.ResourceType\022\016" +
      "\n\006cancel\030\003 \001(\010\022\017\n\007endTime\030\004 \001(\003B:\n\034com.p" +
      "ureland.common.protocalB\032BuildingUpgrade" +
      "ReqProtocal"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_BuildingUpgradeReq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_BuildingUpgradeReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BuildingUpgradeReq_descriptor,
              new java.lang.String[] { "Sid", "ResourceType", "Cancel", "EndTime", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.pureland.common.protocal.vo.ResourceTypeProtocal.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
