// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClanReq.proto

package com.pureland.common.protocal;

public final class ClanReqProtocal {
  private ClanReqProtocal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ClanReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .ClanReq.RequestType requestType = 1;
    /**
     * <code>required .ClanReq.RequestType requestType = 1;</code>
     */
    boolean hasRequestType();
    /**
     * <code>required .ClanReq.RequestType requestType = 1;</code>
     */
    com.pureland.common.protocal.ClanReqProtocal.ClanReq.RequestType getRequestType();

    // optional .ClanBaseVO clanBaseVO = 2;
    /**
     * <code>optional .ClanBaseVO clanBaseVO = 2;</code>
     *
     * <pre>
     *公会基础信息
     * </pre>
     */
    boolean hasClanBaseVO();
    /**
     * <code>optional .ClanBaseVO clanBaseVO = 2;</code>
     *
     * <pre>
     *公会基础信息
     * </pre>
     */
    com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO getClanBaseVO();
    /**
     * <code>optional .ClanBaseVO clanBaseVO = 2;</code>
     *
     * <pre>
     *公会基础信息
     * </pre>
     */
    com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVOOrBuilder getClanBaseVOOrBuilder();

    // optional .ClanSearchConditionVO clanSearchConditionVO = 3;
    /**
     * <code>optional .ClanSearchConditionVO clanSearchConditionVO = 3;</code>
     *
     * <pre>
     *搜索条件
     * </pre>
     */
    boolean hasClanSearchConditionVO();
    /**
     * <code>optional .ClanSearchConditionVO clanSearchConditionVO = 3;</code>
     *
     * <pre>
     *搜索条件
     * </pre>
     */
    com.pureland.common.protocal.vo.ClanSearchConditionVOProtocal.ClanSearchConditionVO getClanSearchConditionVO();
    /**
     * <code>optional .ClanSearchConditionVO clanSearchConditionVO = 3;</code>
     *
     * <pre>
     *搜索条件
     * </pre>
     */
    com.pureland.common.protocal.vo.ClanSearchConditionVOProtocal.ClanSearchConditionVOOrBuilder getClanSearchConditionVOOrBuilder();

    // optional int64 operaId = 4;
    /**
     * <code>optional int64 operaId = 4;</code>
     *
     * <pre>
     *被操作的pid
     * </pre>
     */
    boolean hasOperaId();
    /**
     * <code>optional int64 operaId = 4;</code>
     *
     * <pre>
     *被操作的pid
     * </pre>
     */
    long getOperaId();

    // optional string content = 5;
    /**
     * <code>optional string content = 5;</code>
     *
     * <pre>
     *内容
     * </pre>
     */
    boolean hasContent();
    /**
     * <code>optional string content = 5;</code>
     *
     * <pre>
     *内容
     * </pre>
     */
    java.lang.String getContent();
    /**
     * <code>optional string content = 5;</code>
     *
     * <pre>
     *内容
     * </pre>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    // optional int32 armyId = 6;
    /**
     * <code>optional int32 armyId = 6;</code>
     *
     * <pre>
     *增援的军队
     * </pre>
     */
    boolean hasArmyId();
    /**
     * <code>optional int32 armyId = 6;</code>
     *
     * <pre>
     *增援的军队
     * </pre>
     */
    int getArmyId();

    // optional bytes sound = 7;
    /**
     * <code>optional bytes sound = 7;</code>
     *
     * <pre>
     *语音
     * </pre>
     */
    boolean hasSound();
    /**
     * <code>optional bytes sound = 7;</code>
     *
     * <pre>
     *语音
     * </pre>
     */
    com.google.protobuf.ByteString getSound();
  }
  /**
   * Protobuf type {@code ClanReq}
   */
  public static final class ClanReq extends
      com.google.protobuf.GeneratedMessage
      implements ClanReqOrBuilder {
    // Use ClanReq.newBuilder() to construct.
    private ClanReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ClanReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ClanReq defaultInstance;
    public static ClanReq getDefaultInstance() {
      return defaultInstance;
    }

    public ClanReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ClanReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.pureland.common.protocal.ClanReqProtocal.ClanReq.RequestType value = com.pureland.common.protocal.ClanReqProtocal.ClanReq.RequestType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                requestType_ = value;
              }
              break;
            }
            case 18: {
              com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = clanBaseVO_.toBuilder();
              }
              clanBaseVO_ = input.readMessage(com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(clanBaseVO_);
                clanBaseVO_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              com.pureland.common.protocal.vo.ClanSearchConditionVOProtocal.ClanSearchConditionVO.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = clanSearchConditionVO_.toBuilder();
              }
              clanSearchConditionVO_ = input.readMessage(com.pureland.common.protocal.vo.ClanSearchConditionVOProtocal.ClanSearchConditionVO.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(clanSearchConditionVO_);
                clanSearchConditionVO_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              operaId_ = input.readInt64();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              content_ = input.readBytes();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              armyId_ = input.readInt32();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              sound_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pureland.common.protocal.ClanReqProtocal.internal_static_ClanReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pureland.common.protocal.ClanReqProtocal.internal_static_ClanReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pureland.common.protocal.ClanReqProtocal.ClanReq.class, com.pureland.common.protocal.ClanReqProtocal.ClanReq.Builder.class);
    }

    public static com.google.protobuf.Parser<ClanReq> PARSER =
        new com.google.protobuf.AbstractParser<ClanReq>() {
      public ClanReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClanReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ClanReq> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code ClanReq.RequestType}
     */
    public enum RequestType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>GetClanInfo = 1;</code>
       *
       * <pre>
       *查看公会详细信息
       * </pre>
       */
      GetClanInfo(0, 1),
      /**
       * <code>Search = 2;</code>
       *
       * <pre>
       *搜索请求
       * </pre>
       */
      Search(1, 2),
      /**
       * <code>CreateClan = 3;</code>
       *
       * <pre>
       *创建公会
       * </pre>
       */
      CreateClan(2, 3),
      /**
       * <code>ViewClanMemberInfo = 4;</code>
       *
       * <pre>
       *查看玩家信息
       * </pre>
       */
      ViewClanMemberInfo(3, 4),
      /**
       * <code>VieClanMemberBuilding = 5;</code>
       *
       * <pre>
       *查看玩家建筑
       * </pre>
       */
      VieClanMemberBuilding(4, 5),
      /**
       * <code>JoinClan = 6;</code>
       *
       * <pre>
       *加入公会
       * </pre>
       */
      JoinClan(5, 6),
      /**
       * <code>LeaveClan = 7;</code>
       *
       * <pre>
       *离开公会
       * </pre>
       */
      LeaveClan(6, 7),
      /**
       * <code>ModifyClan = 8;</code>
       *
       * <pre>
       *编辑公会
       * </pre>
       */
      ModifyClan(7, 8),
      /**
       * <code>Kick = 9;</code>
       *
       * <pre>
       *踢人
       * </pre>
       */
      Kick(8, 9),
      /**
       * <code>Promote = 10;</code>
       *
       * <pre>
       *提升
       * </pre>
       */
      Promote(9, 10),
      /**
       * <code>Degrade = 11;</code>
       *
       * <pre>
       *降级	
       * </pre>
       */
      Degrade(10, 11),
      /**
       * <code>SendClanMail = 12;</code>
       *
       * <pre>
       *发送公会邮件
       * </pre>
       */
      SendClanMail(11, 12),
      /**
       * <code>AskForDonate = 13;</code>
       */
      AskForDonate(12, 13),
      /**
       * <code>Donate = 14;</code>
       *
       * <pre>
       *增援
       * </pre>
       */
      Donate(13, 14),
      /**
       * <code>AskForDonateImmediately = 15;</code>
       *
       * <pre>
       *立即增援解除时间
       * </pre>
       */
      AskForDonateImmediately(14, 15),
      ;

      /**
       * <code>GetClanInfo = 1;</code>
       *
       * <pre>
       *查看公会详细信息
       * </pre>
       */
      public static final int GetClanInfo_VALUE = 1;
      /**
       * <code>Search = 2;</code>
       *
       * <pre>
       *搜索请求
       * </pre>
       */
      public static final int Search_VALUE = 2;
      /**
       * <code>CreateClan = 3;</code>
       *
       * <pre>
       *创建公会
       * </pre>
       */
      public static final int CreateClan_VALUE = 3;
      /**
       * <code>ViewClanMemberInfo = 4;</code>
       *
       * <pre>
       *查看玩家信息
       * </pre>
       */
      public static final int ViewClanMemberInfo_VALUE = 4;
      /**
       * <code>VieClanMemberBuilding = 5;</code>
       *
       * <pre>
       *查看玩家建筑
       * </pre>
       */
      public static final int VieClanMemberBuilding_VALUE = 5;
      /**
       * <code>JoinClan = 6;</code>
       *
       * <pre>
       *加入公会
       * </pre>
       */
      public static final int JoinClan_VALUE = 6;
      /**
       * <code>LeaveClan = 7;</code>
       *
       * <pre>
       *离开公会
       * </pre>
       */
      public static final int LeaveClan_VALUE = 7;
      /**
       * <code>ModifyClan = 8;</code>
       *
       * <pre>
       *编辑公会
       * </pre>
       */
      public static final int ModifyClan_VALUE = 8;
      /**
       * <code>Kick = 9;</code>
       *
       * <pre>
       *踢人
       * </pre>
       */
      public static final int Kick_VALUE = 9;
      /**
       * <code>Promote = 10;</code>
       *
       * <pre>
       *提升
       * </pre>
       */
      public static final int Promote_VALUE = 10;
      /**
       * <code>Degrade = 11;</code>
       *
       * <pre>
       *降级	
       * </pre>
       */
      public static final int Degrade_VALUE = 11;
      /**
       * <code>SendClanMail = 12;</code>
       *
       * <pre>
       *发送公会邮件
       * </pre>
       */
      public static final int SendClanMail_VALUE = 12;
      /**
       * <code>AskForDonate = 13;</code>
       */
      public static final int AskForDonate_VALUE = 13;
      /**
       * <code>Donate = 14;</code>
       *
       * <pre>
       *增援
       * </pre>
       */
      public static final int Donate_VALUE = 14;
      /**
       * <code>AskForDonateImmediately = 15;</code>
       *
       * <pre>
       *立即增援解除时间
       * </pre>
       */
      public static final int AskForDonateImmediately_VALUE = 15;


      public final int getNumber() { return value; }

      public static RequestType valueOf(int value) {
        switch (value) {
          case 1: return GetClanInfo;
          case 2: return Search;
          case 3: return CreateClan;
          case 4: return ViewClanMemberInfo;
          case 5: return VieClanMemberBuilding;
          case 6: return JoinClan;
          case 7: return LeaveClan;
          case 8: return ModifyClan;
          case 9: return Kick;
          case 10: return Promote;
          case 11: return Degrade;
          case 12: return SendClanMail;
          case 13: return AskForDonate;
          case 14: return Donate;
          case 15: return AskForDonateImmediately;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<RequestType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
              public RequestType findValueByNumber(int number) {
                return RequestType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.pureland.common.protocal.ClanReqProtocal.ClanReq.getDescriptor().getEnumTypes().get(0);
      }

      private static final RequestType[] VALUES = values();

      public static RequestType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private RequestType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ClanReq.RequestType)
    }

    private int bitField0_;
    // required .ClanReq.RequestType requestType = 1;
    public static final int REQUESTTYPE_FIELD_NUMBER = 1;
    private com.pureland.common.protocal.ClanReqProtocal.ClanReq.RequestType requestType_;
    /**
     * <code>required .ClanReq.RequestType requestType = 1;</code>
     */
    public boolean hasRequestType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .ClanReq.RequestType requestType = 1;</code>
     */
    public com.pureland.common.protocal.ClanReqProtocal.ClanReq.RequestType getRequestType() {
      return requestType_;
    }

    // optional .ClanBaseVO clanBaseVO = 2;
    public static final int CLANBASEVO_FIELD_NUMBER = 2;
    private com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO clanBaseVO_;
    /**
     * <code>optional .ClanBaseVO clanBaseVO = 2;</code>
     *
     * <pre>
     *公会基础信息
     * </pre>
     */
    public boolean hasClanBaseVO() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .ClanBaseVO clanBaseVO = 2;</code>
     *
     * <pre>
     *公会基础信息
     * </pre>
     */
    public com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO getClanBaseVO() {
      return clanBaseVO_;
    }
    /**
     * <code>optional .ClanBaseVO clanBaseVO = 2;</code>
     *
     * <pre>
     *公会基础信息
     * </pre>
     */
    public com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVOOrBuilder getClanBaseVOOrBuilder() {
      return clanBaseVO_;
    }

    // optional .ClanSearchConditionVO clanSearchConditionVO = 3;
    public static final int CLANSEARCHCONDITIONVO_FIELD_NUMBER = 3;
    private com.pureland.common.protocal.vo.ClanSearchConditionVOProtocal.ClanSearchConditionVO clanSearchConditionVO_;
    /**
     * <code>optional .ClanSearchConditionVO clanSearchConditionVO = 3;</code>
     *
     * <pre>
     *搜索条件
     * </pre>
     */
    public boolean hasClanSearchConditionVO() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .ClanSearchConditionVO clanSearchConditionVO = 3;</code>
     *
     * <pre>
     *搜索条件
     * </pre>
     */
    public com.pureland.common.protocal.vo.ClanSearchConditionVOProtocal.ClanSearchConditionVO getClanSearchConditionVO() {
      return clanSearchConditionVO_;
    }
    /**
     * <code>optional .ClanSearchConditionVO clanSearchConditionVO = 3;</code>
     *
     * <pre>
     *搜索条件
     * </pre>
     */
    public com.pureland.common.protocal.vo.ClanSearchConditionVOProtocal.ClanSearchConditionVOOrBuilder getClanSearchConditionVOOrBuilder() {
      return clanSearchConditionVO_;
    }

    // optional int64 operaId = 4;
    public static final int OPERAID_FIELD_NUMBER = 4;
    private long operaId_;
    /**
     * <code>optional int64 operaId = 4;</code>
     *
     * <pre>
     *被操作的pid
     * </pre>
     */
    public boolean hasOperaId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 operaId = 4;</code>
     *
     * <pre>
     *被操作的pid
     * </pre>
     */
    public long getOperaId() {
      return operaId_;
    }

    // optional string content = 5;
    public static final int CONTENT_FIELD_NUMBER = 5;
    private java.lang.Object content_;
    /**
     * <code>optional string content = 5;</code>
     *
     * <pre>
     *内容
     * </pre>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string content = 5;</code>
     *
     * <pre>
     *内容
     * </pre>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string content = 5;</code>
     *
     * <pre>
     *内容
     * </pre>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 armyId = 6;
    public static final int ARMYID_FIELD_NUMBER = 6;
    private int armyId_;
    /**
     * <code>optional int32 armyId = 6;</code>
     *
     * <pre>
     *增援的军队
     * </pre>
     */
    public boolean hasArmyId() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 armyId = 6;</code>
     *
     * <pre>
     *增援的军队
     * </pre>
     */
    public int getArmyId() {
      return armyId_;
    }

    // optional bytes sound = 7;
    public static final int SOUND_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString sound_;
    /**
     * <code>optional bytes sound = 7;</code>
     *
     * <pre>
     *语音
     * </pre>
     */
    public boolean hasSound() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional bytes sound = 7;</code>
     *
     * <pre>
     *语音
     * </pre>
     */
    public com.google.protobuf.ByteString getSound() {
      return sound_;
    }

    private void initFields() {
      requestType_ = com.pureland.common.protocal.ClanReqProtocal.ClanReq.RequestType.GetClanInfo;
      clanBaseVO_ = com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO.getDefaultInstance();
      clanSearchConditionVO_ = com.pureland.common.protocal.vo.ClanSearchConditionVOProtocal.ClanSearchConditionVO.getDefaultInstance();
      operaId_ = 0L;
      content_ = "";
      armyId_ = 0;
      sound_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRequestType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, requestType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, clanBaseVO_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, clanSearchConditionVO_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, operaId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getContentBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, armyId_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, sound_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, requestType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, clanBaseVO_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, clanSearchConditionVO_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, operaId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getContentBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, armyId_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, sound_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.pureland.common.protocal.ClanReqProtocal.ClanReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pureland.common.protocal.ClanReqProtocal.ClanReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pureland.common.protocal.ClanReqProtocal.ClanReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pureland.common.protocal.ClanReqProtocal.ClanReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pureland.common.protocal.ClanReqProtocal.ClanReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.pureland.common.protocal.ClanReqProtocal.ClanReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.pureland.common.protocal.ClanReqProtocal.ClanReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.pureland.common.protocal.ClanReqProtocal.ClanReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.pureland.common.protocal.ClanReqProtocal.ClanReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.pureland.common.protocal.ClanReqProtocal.ClanReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.pureland.common.protocal.ClanReqProtocal.ClanReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ClanReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.pureland.common.protocal.ClanReqProtocal.ClanReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pureland.common.protocal.ClanReqProtocal.internal_static_ClanReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pureland.common.protocal.ClanReqProtocal.internal_static_ClanReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pureland.common.protocal.ClanReqProtocal.ClanReq.class, com.pureland.common.protocal.ClanReqProtocal.ClanReq.Builder.class);
      }

      // Construct using com.pureland.common.protocal.ClanReqProtocal.ClanReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getClanBaseVOFieldBuilder();
          getClanSearchConditionVOFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        requestType_ = com.pureland.common.protocal.ClanReqProtocal.ClanReq.RequestType.GetClanInfo;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (clanBaseVOBuilder_ == null) {
          clanBaseVO_ = com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO.getDefaultInstance();
        } else {
          clanBaseVOBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (clanSearchConditionVOBuilder_ == null) {
          clanSearchConditionVO_ = com.pureland.common.protocal.vo.ClanSearchConditionVOProtocal.ClanSearchConditionVO.getDefaultInstance();
        } else {
          clanSearchConditionVOBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        operaId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        armyId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        sound_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pureland.common.protocal.ClanReqProtocal.internal_static_ClanReq_descriptor;
      }

      public com.pureland.common.protocal.ClanReqProtocal.ClanReq getDefaultInstanceForType() {
        return com.pureland.common.protocal.ClanReqProtocal.ClanReq.getDefaultInstance();
      }

      public com.pureland.common.protocal.ClanReqProtocal.ClanReq build() {
        com.pureland.common.protocal.ClanReqProtocal.ClanReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.pureland.common.protocal.ClanReqProtocal.ClanReq buildPartial() {
        com.pureland.common.protocal.ClanReqProtocal.ClanReq result = new com.pureland.common.protocal.ClanReqProtocal.ClanReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.requestType_ = requestType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (clanBaseVOBuilder_ == null) {
          result.clanBaseVO_ = clanBaseVO_;
        } else {
          result.clanBaseVO_ = clanBaseVOBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (clanSearchConditionVOBuilder_ == null) {
          result.clanSearchConditionVO_ = clanSearchConditionVO_;
        } else {
          result.clanSearchConditionVO_ = clanSearchConditionVOBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.operaId_ = operaId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.content_ = content_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.armyId_ = armyId_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.sound_ = sound_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pureland.common.protocal.ClanReqProtocal.ClanReq) {
          return mergeFrom((com.pureland.common.protocal.ClanReqProtocal.ClanReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.pureland.common.protocal.ClanReqProtocal.ClanReq other) {
        if (other == com.pureland.common.protocal.ClanReqProtocal.ClanReq.getDefaultInstance()) return this;
        if (other.hasRequestType()) {
          setRequestType(other.getRequestType());
        }
        if (other.hasClanBaseVO()) {
          mergeClanBaseVO(other.getClanBaseVO());
        }
        if (other.hasClanSearchConditionVO()) {
          mergeClanSearchConditionVO(other.getClanSearchConditionVO());
        }
        if (other.hasOperaId()) {
          setOperaId(other.getOperaId());
        }
        if (other.hasContent()) {
          bitField0_ |= 0x00000010;
          content_ = other.content_;
          onChanged();
        }
        if (other.hasArmyId()) {
          setArmyId(other.getArmyId());
        }
        if (other.hasSound()) {
          setSound(other.getSound());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRequestType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.pureland.common.protocal.ClanReqProtocal.ClanReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.pureland.common.protocal.ClanReqProtocal.ClanReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .ClanReq.RequestType requestType = 1;
      private com.pureland.common.protocal.ClanReqProtocal.ClanReq.RequestType requestType_ = com.pureland.common.protocal.ClanReqProtocal.ClanReq.RequestType.GetClanInfo;
      /**
       * <code>required .ClanReq.RequestType requestType = 1;</code>
       */
      public boolean hasRequestType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .ClanReq.RequestType requestType = 1;</code>
       */
      public com.pureland.common.protocal.ClanReqProtocal.ClanReq.RequestType getRequestType() {
        return requestType_;
      }
      /**
       * <code>required .ClanReq.RequestType requestType = 1;</code>
       */
      public Builder setRequestType(com.pureland.common.protocal.ClanReqProtocal.ClanReq.RequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        requestType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .ClanReq.RequestType requestType = 1;</code>
       */
      public Builder clearRequestType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        requestType_ = com.pureland.common.protocal.ClanReqProtocal.ClanReq.RequestType.GetClanInfo;
        onChanged();
        return this;
      }

      // optional .ClanBaseVO clanBaseVO = 2;
      private com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO clanBaseVO_ = com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO, com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO.Builder, com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVOOrBuilder> clanBaseVOBuilder_;
      /**
       * <code>optional .ClanBaseVO clanBaseVO = 2;</code>
       *
       * <pre>
       *公会基础信息
       * </pre>
       */
      public boolean hasClanBaseVO() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .ClanBaseVO clanBaseVO = 2;</code>
       *
       * <pre>
       *公会基础信息
       * </pre>
       */
      public com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO getClanBaseVO() {
        if (clanBaseVOBuilder_ == null) {
          return clanBaseVO_;
        } else {
          return clanBaseVOBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ClanBaseVO clanBaseVO = 2;</code>
       *
       * <pre>
       *公会基础信息
       * </pre>
       */
      public Builder setClanBaseVO(com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO value) {
        if (clanBaseVOBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          clanBaseVO_ = value;
          onChanged();
        } else {
          clanBaseVOBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .ClanBaseVO clanBaseVO = 2;</code>
       *
       * <pre>
       *公会基础信息
       * </pre>
       */
      public Builder setClanBaseVO(
          com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO.Builder builderForValue) {
        if (clanBaseVOBuilder_ == null) {
          clanBaseVO_ = builderForValue.build();
          onChanged();
        } else {
          clanBaseVOBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .ClanBaseVO clanBaseVO = 2;</code>
       *
       * <pre>
       *公会基础信息
       * </pre>
       */
      public Builder mergeClanBaseVO(com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO value) {
        if (clanBaseVOBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              clanBaseVO_ != com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO.getDefaultInstance()) {
            clanBaseVO_ =
              com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO.newBuilder(clanBaseVO_).mergeFrom(value).buildPartial();
          } else {
            clanBaseVO_ = value;
          }
          onChanged();
        } else {
          clanBaseVOBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .ClanBaseVO clanBaseVO = 2;</code>
       *
       * <pre>
       *公会基础信息
       * </pre>
       */
      public Builder clearClanBaseVO() {
        if (clanBaseVOBuilder_ == null) {
          clanBaseVO_ = com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO.getDefaultInstance();
          onChanged();
        } else {
          clanBaseVOBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .ClanBaseVO clanBaseVO = 2;</code>
       *
       * <pre>
       *公会基础信息
       * </pre>
       */
      public com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO.Builder getClanBaseVOBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getClanBaseVOFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ClanBaseVO clanBaseVO = 2;</code>
       *
       * <pre>
       *公会基础信息
       * </pre>
       */
      public com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVOOrBuilder getClanBaseVOOrBuilder() {
        if (clanBaseVOBuilder_ != null) {
          return clanBaseVOBuilder_.getMessageOrBuilder();
        } else {
          return clanBaseVO_;
        }
      }
      /**
       * <code>optional .ClanBaseVO clanBaseVO = 2;</code>
       *
       * <pre>
       *公会基础信息
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO, com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO.Builder, com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVOOrBuilder> 
          getClanBaseVOFieldBuilder() {
        if (clanBaseVOBuilder_ == null) {
          clanBaseVOBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO, com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO.Builder, com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVOOrBuilder>(
                  clanBaseVO_,
                  getParentForChildren(),
                  isClean());
          clanBaseVO_ = null;
        }
        return clanBaseVOBuilder_;
      }

      // optional .ClanSearchConditionVO clanSearchConditionVO = 3;
      private com.pureland.common.protocal.vo.ClanSearchConditionVOProtocal.ClanSearchConditionVO clanSearchConditionVO_ = com.pureland.common.protocal.vo.ClanSearchConditionVOProtocal.ClanSearchConditionVO.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.pureland.common.protocal.vo.ClanSearchConditionVOProtocal.ClanSearchConditionVO, com.pureland.common.protocal.vo.ClanSearchConditionVOProtocal.ClanSearchConditionVO.Builder, com.pureland.common.protocal.vo.ClanSearchConditionVOProtocal.ClanSearchConditionVOOrBuilder> clanSearchConditionVOBuilder_;
      /**
       * <code>optional .ClanSearchConditionVO clanSearchConditionVO = 3;</code>
       *
       * <pre>
       *搜索条件
       * </pre>
       */
      public boolean hasClanSearchConditionVO() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .ClanSearchConditionVO clanSearchConditionVO = 3;</code>
       *
       * <pre>
       *搜索条件
       * </pre>
       */
      public com.pureland.common.protocal.vo.ClanSearchConditionVOProtocal.ClanSearchConditionVO getClanSearchConditionVO() {
        if (clanSearchConditionVOBuilder_ == null) {
          return clanSearchConditionVO_;
        } else {
          return clanSearchConditionVOBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ClanSearchConditionVO clanSearchConditionVO = 3;</code>
       *
       * <pre>
       *搜索条件
       * </pre>
       */
      public Builder setClanSearchConditionVO(com.pureland.common.protocal.vo.ClanSearchConditionVOProtocal.ClanSearchConditionVO value) {
        if (clanSearchConditionVOBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          clanSearchConditionVO_ = value;
          onChanged();
        } else {
          clanSearchConditionVOBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .ClanSearchConditionVO clanSearchConditionVO = 3;</code>
       *
       * <pre>
       *搜索条件
       * </pre>
       */
      public Builder setClanSearchConditionVO(
          com.pureland.common.protocal.vo.ClanSearchConditionVOProtocal.ClanSearchConditionVO.Builder builderForValue) {
        if (clanSearchConditionVOBuilder_ == null) {
          clanSearchConditionVO_ = builderForValue.build();
          onChanged();
        } else {
          clanSearchConditionVOBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .ClanSearchConditionVO clanSearchConditionVO = 3;</code>
       *
       * <pre>
       *搜索条件
       * </pre>
       */
      public Builder mergeClanSearchConditionVO(com.pureland.common.protocal.vo.ClanSearchConditionVOProtocal.ClanSearchConditionVO value) {
        if (clanSearchConditionVOBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              clanSearchConditionVO_ != com.pureland.common.protocal.vo.ClanSearchConditionVOProtocal.ClanSearchConditionVO.getDefaultInstance()) {
            clanSearchConditionVO_ =
              com.pureland.common.protocal.vo.ClanSearchConditionVOProtocal.ClanSearchConditionVO.newBuilder(clanSearchConditionVO_).mergeFrom(value).buildPartial();
          } else {
            clanSearchConditionVO_ = value;
          }
          onChanged();
        } else {
          clanSearchConditionVOBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .ClanSearchConditionVO clanSearchConditionVO = 3;</code>
       *
       * <pre>
       *搜索条件
       * </pre>
       */
      public Builder clearClanSearchConditionVO() {
        if (clanSearchConditionVOBuilder_ == null) {
          clanSearchConditionVO_ = com.pureland.common.protocal.vo.ClanSearchConditionVOProtocal.ClanSearchConditionVO.getDefaultInstance();
          onChanged();
        } else {
          clanSearchConditionVOBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .ClanSearchConditionVO clanSearchConditionVO = 3;</code>
       *
       * <pre>
       *搜索条件
       * </pre>
       */
      public com.pureland.common.protocal.vo.ClanSearchConditionVOProtocal.ClanSearchConditionVO.Builder getClanSearchConditionVOBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getClanSearchConditionVOFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ClanSearchConditionVO clanSearchConditionVO = 3;</code>
       *
       * <pre>
       *搜索条件
       * </pre>
       */
      public com.pureland.common.protocal.vo.ClanSearchConditionVOProtocal.ClanSearchConditionVOOrBuilder getClanSearchConditionVOOrBuilder() {
        if (clanSearchConditionVOBuilder_ != null) {
          return clanSearchConditionVOBuilder_.getMessageOrBuilder();
        } else {
          return clanSearchConditionVO_;
        }
      }
      /**
       * <code>optional .ClanSearchConditionVO clanSearchConditionVO = 3;</code>
       *
       * <pre>
       *搜索条件
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.pureland.common.protocal.vo.ClanSearchConditionVOProtocal.ClanSearchConditionVO, com.pureland.common.protocal.vo.ClanSearchConditionVOProtocal.ClanSearchConditionVO.Builder, com.pureland.common.protocal.vo.ClanSearchConditionVOProtocal.ClanSearchConditionVOOrBuilder> 
          getClanSearchConditionVOFieldBuilder() {
        if (clanSearchConditionVOBuilder_ == null) {
          clanSearchConditionVOBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.pureland.common.protocal.vo.ClanSearchConditionVOProtocal.ClanSearchConditionVO, com.pureland.common.protocal.vo.ClanSearchConditionVOProtocal.ClanSearchConditionVO.Builder, com.pureland.common.protocal.vo.ClanSearchConditionVOProtocal.ClanSearchConditionVOOrBuilder>(
                  clanSearchConditionVO_,
                  getParentForChildren(),
                  isClean());
          clanSearchConditionVO_ = null;
        }
        return clanSearchConditionVOBuilder_;
      }

      // optional int64 operaId = 4;
      private long operaId_ ;
      /**
       * <code>optional int64 operaId = 4;</code>
       *
       * <pre>
       *被操作的pid
       * </pre>
       */
      public boolean hasOperaId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 operaId = 4;</code>
       *
       * <pre>
       *被操作的pid
       * </pre>
       */
      public long getOperaId() {
        return operaId_;
      }
      /**
       * <code>optional int64 operaId = 4;</code>
       *
       * <pre>
       *被操作的pid
       * </pre>
       */
      public Builder setOperaId(long value) {
        bitField0_ |= 0x00000008;
        operaId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 operaId = 4;</code>
       *
       * <pre>
       *被操作的pid
       * </pre>
       */
      public Builder clearOperaId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        operaId_ = 0L;
        onChanged();
        return this;
      }

      // optional string content = 5;
      private java.lang.Object content_ = "";
      /**
       * <code>optional string content = 5;</code>
       *
       * <pre>
       *内容
       * </pre>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string content = 5;</code>
       *
       * <pre>
       *内容
       * </pre>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string content = 5;</code>
       *
       * <pre>
       *内容
       * </pre>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string content = 5;</code>
       *
       * <pre>
       *内容
       * </pre>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 5;</code>
       *
       * <pre>
       *内容
       * </pre>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000010);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 5;</code>
       *
       * <pre>
       *内容
       * </pre>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        content_ = value;
        onChanged();
        return this;
      }

      // optional int32 armyId = 6;
      private int armyId_ ;
      /**
       * <code>optional int32 armyId = 6;</code>
       *
       * <pre>
       *增援的军队
       * </pre>
       */
      public boolean hasArmyId() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 armyId = 6;</code>
       *
       * <pre>
       *增援的军队
       * </pre>
       */
      public int getArmyId() {
        return armyId_;
      }
      /**
       * <code>optional int32 armyId = 6;</code>
       *
       * <pre>
       *增援的军队
       * </pre>
       */
      public Builder setArmyId(int value) {
        bitField0_ |= 0x00000020;
        armyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 armyId = 6;</code>
       *
       * <pre>
       *增援的军队
       * </pre>
       */
      public Builder clearArmyId() {
        bitField0_ = (bitField0_ & ~0x00000020);
        armyId_ = 0;
        onChanged();
        return this;
      }

      // optional bytes sound = 7;
      private com.google.protobuf.ByteString sound_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes sound = 7;</code>
       *
       * <pre>
       *语音
       * </pre>
       */
      public boolean hasSound() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional bytes sound = 7;</code>
       *
       * <pre>
       *语音
       * </pre>
       */
      public com.google.protobuf.ByteString getSound() {
        return sound_;
      }
      /**
       * <code>optional bytes sound = 7;</code>
       *
       * <pre>
       *语音
       * </pre>
       */
      public Builder setSound(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        sound_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes sound = 7;</code>
       *
       * <pre>
       *语音
       * </pre>
       */
      public Builder clearSound() {
        bitField0_ = (bitField0_ & ~0x00000040);
        sound_ = getDefaultInstance().getSound();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ClanReq)
    }

    static {
      defaultInstance = new ClanReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ClanReq)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ClanReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ClanReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rClanReq.proto\032\020ClanBaseVO.proto\032\033ClanS" +
      "earchConditionVO.proto\"\333\003\n\007ClanReq\022)\n\013re" +
      "questType\030\001 \002(\0162\024.ClanReq.RequestType\022\037\n" +
      "\nclanBaseVO\030\002 \001(\0132\013.ClanBaseVO\0225\n\025clanSe" +
      "archConditionVO\030\003 \001(\0132\026.ClanSearchCondit" +
      "ionVO\022\017\n\007operaId\030\004 \001(\003\022\017\n\007content\030\005 \001(\t\022" +
      "\016\n\006armyId\030\006 \001(\005\022\r\n\005sound\030\007 \001(\014\"\213\002\n\013Reque" +
      "stType\022\017\n\013GetClanInfo\020\001\022\n\n\006Search\020\002\022\016\n\nC" +
      "reateClan\020\003\022\026\n\022ViewClanMemberInfo\020\004\022\031\n\025V" +
      "ieClanMemberBuilding\020\005\022\014\n\010JoinClan\020\006\022\r\n\t",
      "LeaveClan\020\007\022\016\n\nModifyClan\020\010\022\010\n\004Kick\020\t\022\013\n" +
      "\007Promote\020\n\022\013\n\007Degrade\020\013\022\020\n\014SendClanMail\020" +
      "\014\022\020\n\014AskForDonate\020\r\022\n\n\006Donate\020\016\022\033\n\027AskFo" +
      "rDonateImmediately\020\017B/\n\034com.pureland.com" +
      "mon.protocalB\017ClanReqProtocal"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ClanReq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ClanReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ClanReq_descriptor,
              new java.lang.String[] { "RequestType", "ClanBaseVO", "ClanSearchConditionVO", "OperaId", "Content", "ArmyId", "Sound", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.pureland.common.protocal.vo.ClanBaseVOProtocal.getDescriptor(),
          com.pureland.common.protocal.vo.ClanSearchConditionVOProtocal.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
