// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClanResp.proto

package com.pureland.common.protocal;

public final class ClanRespProtocal {
  private ClanRespProtocal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ClanRespOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .ClanVO clanVO = 1;
    /**
     * <code>repeated .ClanVO clanVO = 1;</code>
     *
     * <pre>
     *公会信息
     * </pre>
     */
    java.util.List<com.pureland.common.protocal.vo.ClanVOProtocal.ClanVO> 
        getClanVOList();
    /**
     * <code>repeated .ClanVO clanVO = 1;</code>
     *
     * <pre>
     *公会信息
     * </pre>
     */
    com.pureland.common.protocal.vo.ClanVOProtocal.ClanVO getClanVO(int index);
    /**
     * <code>repeated .ClanVO clanVO = 1;</code>
     *
     * <pre>
     *公会信息
     * </pre>
     */
    int getClanVOCount();
    /**
     * <code>repeated .ClanVO clanVO = 1;</code>
     *
     * <pre>
     *公会信息
     * </pre>
     */
    java.util.List<? extends com.pureland.common.protocal.vo.ClanVOProtocal.ClanVOOrBuilder> 
        getClanVOOrBuilderList();
    /**
     * <code>repeated .ClanVO clanVO = 1;</code>
     *
     * <pre>
     *公会信息
     * </pre>
     */
    com.pureland.common.protocal.vo.ClanVOProtocal.ClanVOOrBuilder getClanVOOrBuilder(
        int index);

    // optional int32 clearDonateTimeDiamond = 2;
    /**
     * <code>optional int32 clearDonateTimeDiamond = 2;</code>
     *
     * <pre>
     *清除公会增援CD
     * </pre>
     */
    boolean hasClearDonateTimeDiamond();
    /**
     * <code>optional int32 clearDonateTimeDiamond = 2;</code>
     *
     * <pre>
     *清除公会增援CD
     * </pre>
     */
    int getClearDonateTimeDiamond();
  }
  /**
   * Protobuf type {@code ClanResp}
   */
  public static final class ClanResp extends
      com.google.protobuf.GeneratedMessage
      implements ClanRespOrBuilder {
    // Use ClanResp.newBuilder() to construct.
    private ClanResp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ClanResp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ClanResp defaultInstance;
    public static ClanResp getDefaultInstance() {
      return defaultInstance;
    }

    public ClanResp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ClanResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                clanVO_ = new java.util.ArrayList<com.pureland.common.protocal.vo.ClanVOProtocal.ClanVO>();
                mutable_bitField0_ |= 0x00000001;
              }
              clanVO_.add(input.readMessage(com.pureland.common.protocal.vo.ClanVOProtocal.ClanVO.PARSER, extensionRegistry));
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              clearDonateTimeDiamond_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          clanVO_ = java.util.Collections.unmodifiableList(clanVO_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pureland.common.protocal.ClanRespProtocal.internal_static_ClanResp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pureland.common.protocal.ClanRespProtocal.internal_static_ClanResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pureland.common.protocal.ClanRespProtocal.ClanResp.class, com.pureland.common.protocal.ClanRespProtocal.ClanResp.Builder.class);
    }

    public static com.google.protobuf.Parser<ClanResp> PARSER =
        new com.google.protobuf.AbstractParser<ClanResp>() {
      public ClanResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClanResp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ClanResp> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // repeated .ClanVO clanVO = 1;
    public static final int CLANVO_FIELD_NUMBER = 1;
    private java.util.List<com.pureland.common.protocal.vo.ClanVOProtocal.ClanVO> clanVO_;
    /**
     * <code>repeated .ClanVO clanVO = 1;</code>
     *
     * <pre>
     *公会信息
     * </pre>
     */
    public java.util.List<com.pureland.common.protocal.vo.ClanVOProtocal.ClanVO> getClanVOList() {
      return clanVO_;
    }
    /**
     * <code>repeated .ClanVO clanVO = 1;</code>
     *
     * <pre>
     *公会信息
     * </pre>
     */
    public java.util.List<? extends com.pureland.common.protocal.vo.ClanVOProtocal.ClanVOOrBuilder> 
        getClanVOOrBuilderList() {
      return clanVO_;
    }
    /**
     * <code>repeated .ClanVO clanVO = 1;</code>
     *
     * <pre>
     *公会信息
     * </pre>
     */
    public int getClanVOCount() {
      return clanVO_.size();
    }
    /**
     * <code>repeated .ClanVO clanVO = 1;</code>
     *
     * <pre>
     *公会信息
     * </pre>
     */
    public com.pureland.common.protocal.vo.ClanVOProtocal.ClanVO getClanVO(int index) {
      return clanVO_.get(index);
    }
    /**
     * <code>repeated .ClanVO clanVO = 1;</code>
     *
     * <pre>
     *公会信息
     * </pre>
     */
    public com.pureland.common.protocal.vo.ClanVOProtocal.ClanVOOrBuilder getClanVOOrBuilder(
        int index) {
      return clanVO_.get(index);
    }

    // optional int32 clearDonateTimeDiamond = 2;
    public static final int CLEARDONATETIMEDIAMOND_FIELD_NUMBER = 2;
    private int clearDonateTimeDiamond_;
    /**
     * <code>optional int32 clearDonateTimeDiamond = 2;</code>
     *
     * <pre>
     *清除公会增援CD
     * </pre>
     */
    public boolean hasClearDonateTimeDiamond() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 clearDonateTimeDiamond = 2;</code>
     *
     * <pre>
     *清除公会增援CD
     * </pre>
     */
    public int getClearDonateTimeDiamond() {
      return clearDonateTimeDiamond_;
    }

    private void initFields() {
      clanVO_ = java.util.Collections.emptyList();
      clearDonateTimeDiamond_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getClanVOCount(); i++) {
        if (!getClanVO(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < clanVO_.size(); i++) {
        output.writeMessage(1, clanVO_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(2, clearDonateTimeDiamond_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < clanVO_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, clanVO_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, clearDonateTimeDiamond_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.pureland.common.protocal.ClanRespProtocal.ClanResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pureland.common.protocal.ClanRespProtocal.ClanResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pureland.common.protocal.ClanRespProtocal.ClanResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pureland.common.protocal.ClanRespProtocal.ClanResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pureland.common.protocal.ClanRespProtocal.ClanResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.pureland.common.protocal.ClanRespProtocal.ClanResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.pureland.common.protocal.ClanRespProtocal.ClanResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.pureland.common.protocal.ClanRespProtocal.ClanResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.pureland.common.protocal.ClanRespProtocal.ClanResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.pureland.common.protocal.ClanRespProtocal.ClanResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.pureland.common.protocal.ClanRespProtocal.ClanResp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ClanResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.pureland.common.protocal.ClanRespProtocal.ClanRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pureland.common.protocal.ClanRespProtocal.internal_static_ClanResp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pureland.common.protocal.ClanRespProtocal.internal_static_ClanResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pureland.common.protocal.ClanRespProtocal.ClanResp.class, com.pureland.common.protocal.ClanRespProtocal.ClanResp.Builder.class);
      }

      // Construct using com.pureland.common.protocal.ClanRespProtocal.ClanResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getClanVOFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (clanVOBuilder_ == null) {
          clanVO_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          clanVOBuilder_.clear();
        }
        clearDonateTimeDiamond_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pureland.common.protocal.ClanRespProtocal.internal_static_ClanResp_descriptor;
      }

      public com.pureland.common.protocal.ClanRespProtocal.ClanResp getDefaultInstanceForType() {
        return com.pureland.common.protocal.ClanRespProtocal.ClanResp.getDefaultInstance();
      }

      public com.pureland.common.protocal.ClanRespProtocal.ClanResp build() {
        com.pureland.common.protocal.ClanRespProtocal.ClanResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.pureland.common.protocal.ClanRespProtocal.ClanResp buildPartial() {
        com.pureland.common.protocal.ClanRespProtocal.ClanResp result = new com.pureland.common.protocal.ClanRespProtocal.ClanResp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (clanVOBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            clanVO_ = java.util.Collections.unmodifiableList(clanVO_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.clanVO_ = clanVO_;
        } else {
          result.clanVO_ = clanVOBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.clearDonateTimeDiamond_ = clearDonateTimeDiamond_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pureland.common.protocal.ClanRespProtocal.ClanResp) {
          return mergeFrom((com.pureland.common.protocal.ClanRespProtocal.ClanResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.pureland.common.protocal.ClanRespProtocal.ClanResp other) {
        if (other == com.pureland.common.protocal.ClanRespProtocal.ClanResp.getDefaultInstance()) return this;
        if (clanVOBuilder_ == null) {
          if (!other.clanVO_.isEmpty()) {
            if (clanVO_.isEmpty()) {
              clanVO_ = other.clanVO_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureClanVOIsMutable();
              clanVO_.addAll(other.clanVO_);
            }
            onChanged();
          }
        } else {
          if (!other.clanVO_.isEmpty()) {
            if (clanVOBuilder_.isEmpty()) {
              clanVOBuilder_.dispose();
              clanVOBuilder_ = null;
              clanVO_ = other.clanVO_;
              bitField0_ = (bitField0_ & ~0x00000001);
              clanVOBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getClanVOFieldBuilder() : null;
            } else {
              clanVOBuilder_.addAllMessages(other.clanVO_);
            }
          }
        }
        if (other.hasClearDonateTimeDiamond()) {
          setClearDonateTimeDiamond(other.getClearDonateTimeDiamond());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getClanVOCount(); i++) {
          if (!getClanVO(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.pureland.common.protocal.ClanRespProtocal.ClanResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.pureland.common.protocal.ClanRespProtocal.ClanResp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .ClanVO clanVO = 1;
      private java.util.List<com.pureland.common.protocal.vo.ClanVOProtocal.ClanVO> clanVO_ =
        java.util.Collections.emptyList();
      private void ensureClanVOIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          clanVO_ = new java.util.ArrayList<com.pureland.common.protocal.vo.ClanVOProtocal.ClanVO>(clanVO_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.pureland.common.protocal.vo.ClanVOProtocal.ClanVO, com.pureland.common.protocal.vo.ClanVOProtocal.ClanVO.Builder, com.pureland.common.protocal.vo.ClanVOProtocal.ClanVOOrBuilder> clanVOBuilder_;

      /**
       * <code>repeated .ClanVO clanVO = 1;</code>
       *
       * <pre>
       *公会信息
       * </pre>
       */
      public java.util.List<com.pureland.common.protocal.vo.ClanVOProtocal.ClanVO> getClanVOList() {
        if (clanVOBuilder_ == null) {
          return java.util.Collections.unmodifiableList(clanVO_);
        } else {
          return clanVOBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ClanVO clanVO = 1;</code>
       *
       * <pre>
       *公会信息
       * </pre>
       */
      public int getClanVOCount() {
        if (clanVOBuilder_ == null) {
          return clanVO_.size();
        } else {
          return clanVOBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ClanVO clanVO = 1;</code>
       *
       * <pre>
       *公会信息
       * </pre>
       */
      public com.pureland.common.protocal.vo.ClanVOProtocal.ClanVO getClanVO(int index) {
        if (clanVOBuilder_ == null) {
          return clanVO_.get(index);
        } else {
          return clanVOBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ClanVO clanVO = 1;</code>
       *
       * <pre>
       *公会信息
       * </pre>
       */
      public Builder setClanVO(
          int index, com.pureland.common.protocal.vo.ClanVOProtocal.ClanVO value) {
        if (clanVOBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureClanVOIsMutable();
          clanVO_.set(index, value);
          onChanged();
        } else {
          clanVOBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ClanVO clanVO = 1;</code>
       *
       * <pre>
       *公会信息
       * </pre>
       */
      public Builder setClanVO(
          int index, com.pureland.common.protocal.vo.ClanVOProtocal.ClanVO.Builder builderForValue) {
        if (clanVOBuilder_ == null) {
          ensureClanVOIsMutable();
          clanVO_.set(index, builderForValue.build());
          onChanged();
        } else {
          clanVOBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ClanVO clanVO = 1;</code>
       *
       * <pre>
       *公会信息
       * </pre>
       */
      public Builder addClanVO(com.pureland.common.protocal.vo.ClanVOProtocal.ClanVO value) {
        if (clanVOBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureClanVOIsMutable();
          clanVO_.add(value);
          onChanged();
        } else {
          clanVOBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ClanVO clanVO = 1;</code>
       *
       * <pre>
       *公会信息
       * </pre>
       */
      public Builder addClanVO(
          int index, com.pureland.common.protocal.vo.ClanVOProtocal.ClanVO value) {
        if (clanVOBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureClanVOIsMutable();
          clanVO_.add(index, value);
          onChanged();
        } else {
          clanVOBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ClanVO clanVO = 1;</code>
       *
       * <pre>
       *公会信息
       * </pre>
       */
      public Builder addClanVO(
          com.pureland.common.protocal.vo.ClanVOProtocal.ClanVO.Builder builderForValue) {
        if (clanVOBuilder_ == null) {
          ensureClanVOIsMutable();
          clanVO_.add(builderForValue.build());
          onChanged();
        } else {
          clanVOBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ClanVO clanVO = 1;</code>
       *
       * <pre>
       *公会信息
       * </pre>
       */
      public Builder addClanVO(
          int index, com.pureland.common.protocal.vo.ClanVOProtocal.ClanVO.Builder builderForValue) {
        if (clanVOBuilder_ == null) {
          ensureClanVOIsMutable();
          clanVO_.add(index, builderForValue.build());
          onChanged();
        } else {
          clanVOBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ClanVO clanVO = 1;</code>
       *
       * <pre>
       *公会信息
       * </pre>
       */
      public Builder addAllClanVO(
          java.lang.Iterable<? extends com.pureland.common.protocal.vo.ClanVOProtocal.ClanVO> values) {
        if (clanVOBuilder_ == null) {
          ensureClanVOIsMutable();
          super.addAll(values, clanVO_);
          onChanged();
        } else {
          clanVOBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ClanVO clanVO = 1;</code>
       *
       * <pre>
       *公会信息
       * </pre>
       */
      public Builder clearClanVO() {
        if (clanVOBuilder_ == null) {
          clanVO_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          clanVOBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ClanVO clanVO = 1;</code>
       *
       * <pre>
       *公会信息
       * </pre>
       */
      public Builder removeClanVO(int index) {
        if (clanVOBuilder_ == null) {
          ensureClanVOIsMutable();
          clanVO_.remove(index);
          onChanged();
        } else {
          clanVOBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ClanVO clanVO = 1;</code>
       *
       * <pre>
       *公会信息
       * </pre>
       */
      public com.pureland.common.protocal.vo.ClanVOProtocal.ClanVO.Builder getClanVOBuilder(
          int index) {
        return getClanVOFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ClanVO clanVO = 1;</code>
       *
       * <pre>
       *公会信息
       * </pre>
       */
      public com.pureland.common.protocal.vo.ClanVOProtocal.ClanVOOrBuilder getClanVOOrBuilder(
          int index) {
        if (clanVOBuilder_ == null) {
          return clanVO_.get(index);  } else {
          return clanVOBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ClanVO clanVO = 1;</code>
       *
       * <pre>
       *公会信息
       * </pre>
       */
      public java.util.List<? extends com.pureland.common.protocal.vo.ClanVOProtocal.ClanVOOrBuilder> 
           getClanVOOrBuilderList() {
        if (clanVOBuilder_ != null) {
          return clanVOBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(clanVO_);
        }
      }
      /**
       * <code>repeated .ClanVO clanVO = 1;</code>
       *
       * <pre>
       *公会信息
       * </pre>
       */
      public com.pureland.common.protocal.vo.ClanVOProtocal.ClanVO.Builder addClanVOBuilder() {
        return getClanVOFieldBuilder().addBuilder(
            com.pureland.common.protocal.vo.ClanVOProtocal.ClanVO.getDefaultInstance());
      }
      /**
       * <code>repeated .ClanVO clanVO = 1;</code>
       *
       * <pre>
       *公会信息
       * </pre>
       */
      public com.pureland.common.protocal.vo.ClanVOProtocal.ClanVO.Builder addClanVOBuilder(
          int index) {
        return getClanVOFieldBuilder().addBuilder(
            index, com.pureland.common.protocal.vo.ClanVOProtocal.ClanVO.getDefaultInstance());
      }
      /**
       * <code>repeated .ClanVO clanVO = 1;</code>
       *
       * <pre>
       *公会信息
       * </pre>
       */
      public java.util.List<com.pureland.common.protocal.vo.ClanVOProtocal.ClanVO.Builder> 
           getClanVOBuilderList() {
        return getClanVOFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.pureland.common.protocal.vo.ClanVOProtocal.ClanVO, com.pureland.common.protocal.vo.ClanVOProtocal.ClanVO.Builder, com.pureland.common.protocal.vo.ClanVOProtocal.ClanVOOrBuilder> 
          getClanVOFieldBuilder() {
        if (clanVOBuilder_ == null) {
          clanVOBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.pureland.common.protocal.vo.ClanVOProtocal.ClanVO, com.pureland.common.protocal.vo.ClanVOProtocal.ClanVO.Builder, com.pureland.common.protocal.vo.ClanVOProtocal.ClanVOOrBuilder>(
                  clanVO_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          clanVO_ = null;
        }
        return clanVOBuilder_;
      }

      // optional int32 clearDonateTimeDiamond = 2;
      private int clearDonateTimeDiamond_ ;
      /**
       * <code>optional int32 clearDonateTimeDiamond = 2;</code>
       *
       * <pre>
       *清除公会增援CD
       * </pre>
       */
      public boolean hasClearDonateTimeDiamond() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 clearDonateTimeDiamond = 2;</code>
       *
       * <pre>
       *清除公会增援CD
       * </pre>
       */
      public int getClearDonateTimeDiamond() {
        return clearDonateTimeDiamond_;
      }
      /**
       * <code>optional int32 clearDonateTimeDiamond = 2;</code>
       *
       * <pre>
       *清除公会增援CD
       * </pre>
       */
      public Builder setClearDonateTimeDiamond(int value) {
        bitField0_ |= 0x00000002;
        clearDonateTimeDiamond_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 clearDonateTimeDiamond = 2;</code>
       *
       * <pre>
       *清除公会增援CD
       * </pre>
       */
      public Builder clearClearDonateTimeDiamond() {
        bitField0_ = (bitField0_ & ~0x00000002);
        clearDonateTimeDiamond_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ClanResp)
    }

    static {
      defaultInstance = new ClanResp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ClanResp)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ClanResp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ClanResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016ClanResp.proto\032\014ClanVO.proto\"C\n\010ClanRe" +
      "sp\022\027\n\006clanVO\030\001 \003(\0132\007.ClanVO\022\036\n\026clearDona" +
      "teTimeDiamond\030\002 \001(\005B0\n\034com.pureland.comm" +
      "on.protocalB\020ClanRespProtocal"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ClanResp_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ClanResp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ClanResp_descriptor,
              new java.lang.String[] { "ClanVO", "ClearDonateTimeDiamond", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.pureland.common.protocal.vo.ClanVOProtocal.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
