// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DeleteArmiesReq.proto

package com.pureland.common.protocal;

public final class DeleteArmiesReqProtocal {
  private DeleteArmiesReqProtocal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DeleteArmiesReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .ArmyVO deleteArmies = 1;
    /**
     * <code>repeated .ArmyVO deleteArmies = 1;</code>
     *
     * <pre>
     *Ҫɾ��ľ��
     * </pre>
     */
    java.util.List<com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO> 
        getDeleteArmiesList();
    /**
     * <code>repeated .ArmyVO deleteArmies = 1;</code>
     *
     * <pre>
     *Ҫɾ��ľ��
     * </pre>
     */
    com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO getDeleteArmies(int index);
    /**
     * <code>repeated .ArmyVO deleteArmies = 1;</code>
     *
     * <pre>
     *Ҫɾ��ľ��
     * </pre>
     */
    int getDeleteArmiesCount();
    /**
     * <code>repeated .ArmyVO deleteArmies = 1;</code>
     *
     * <pre>
     *Ҫɾ��ľ��
     * </pre>
     */
    java.util.List<? extends com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVOOrBuilder> 
        getDeleteArmiesOrBuilderList();
    /**
     * <code>repeated .ArmyVO deleteArmies = 1;</code>
     *
     * <pre>
     *Ҫɾ��ľ��
     * </pre>
     */
    com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVOOrBuilder getDeleteArmiesOrBuilder(
        int index);

    // required .DeleteArmiesReq.DeleteType deleteType = 2;
    /**
     * <code>required .DeleteArmiesReq.DeleteType deleteType = 2;</code>
     *
     * <pre>
     *ɾ�������
     * </pre>
     */
    boolean hasDeleteType();
    /**
     * <code>required .DeleteArmiesReq.DeleteType deleteType = 2;</code>
     *
     * <pre>
     *ɾ�������
     * </pre>
     */
    com.pureland.common.protocal.DeleteArmiesReqProtocal.DeleteArmiesReq.DeleteType getDeleteType();
  }
  /**
   * Protobuf type {@code DeleteArmiesReq}
   *
   * <pre>
   *�������彨��
   * </pre>
   */
  public static final class DeleteArmiesReq extends
      com.google.protobuf.GeneratedMessage
      implements DeleteArmiesReqOrBuilder {
    // Use DeleteArmiesReq.newBuilder() to construct.
    private DeleteArmiesReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DeleteArmiesReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DeleteArmiesReq defaultInstance;
    public static DeleteArmiesReq getDefaultInstance() {
      return defaultInstance;
    }

    public DeleteArmiesReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DeleteArmiesReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                deleteArmies_ = new java.util.ArrayList<com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO>();
                mutable_bitField0_ |= 0x00000001;
              }
              deleteArmies_.add(input.readMessage(com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO.PARSER, extensionRegistry));
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.pureland.common.protocal.DeleteArmiesReqProtocal.DeleteArmiesReq.DeleteType value = com.pureland.common.protocal.DeleteArmiesReqProtocal.DeleteArmiesReq.DeleteType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                deleteType_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          deleteArmies_ = java.util.Collections.unmodifiableList(deleteArmies_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pureland.common.protocal.DeleteArmiesReqProtocal.internal_static_DeleteArmiesReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pureland.common.protocal.DeleteArmiesReqProtocal.internal_static_DeleteArmiesReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pureland.common.protocal.DeleteArmiesReqProtocal.DeleteArmiesReq.class, com.pureland.common.protocal.DeleteArmiesReqProtocal.DeleteArmiesReq.Builder.class);
    }

    public static com.google.protobuf.Parser<DeleteArmiesReq> PARSER =
        new com.google.protobuf.AbstractParser<DeleteArmiesReq>() {
      public DeleteArmiesReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DeleteArmiesReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DeleteArmiesReq> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code DeleteArmiesReq.DeleteType}
     */
    public enum DeleteType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>Barrack = 1;</code>
       *
       * <pre>
       *��Ӫ
       * </pre>
       */
      Barrack(0, 1),
      /**
       * <code>Federal = 2;</code>
       *
       * <pre>
       *����
       * </pre>
       */
      Federal(1, 2),
      ;

      /**
       * <code>Barrack = 1;</code>
       *
       * <pre>
       *��Ӫ
       * </pre>
       */
      public static final int Barrack_VALUE = 1;
      /**
       * <code>Federal = 2;</code>
       *
       * <pre>
       *����
       * </pre>
       */
      public static final int Federal_VALUE = 2;


      public final int getNumber() { return value; }

      public static DeleteType valueOf(int value) {
        switch (value) {
          case 1: return Barrack;
          case 2: return Federal;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DeleteType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<DeleteType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DeleteType>() {
              public DeleteType findValueByNumber(int number) {
                return DeleteType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.pureland.common.protocal.DeleteArmiesReqProtocal.DeleteArmiesReq.getDescriptor().getEnumTypes().get(0);
      }

      private static final DeleteType[] VALUES = values();

      public static DeleteType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private DeleteType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:DeleteArmiesReq.DeleteType)
    }

    private int bitField0_;
    // repeated .ArmyVO deleteArmies = 1;
    public static final int DELETEARMIES_FIELD_NUMBER = 1;
    private java.util.List<com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO> deleteArmies_;
    /**
     * <code>repeated .ArmyVO deleteArmies = 1;</code>
     *
     * <pre>
     *Ҫɾ��ľ��
     * </pre>
     */
    public java.util.List<com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO> getDeleteArmiesList() {
      return deleteArmies_;
    }
    /**
     * <code>repeated .ArmyVO deleteArmies = 1;</code>
     *
     * <pre>
     *Ҫɾ��ľ��
     * </pre>
     */
    public java.util.List<? extends com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVOOrBuilder> 
        getDeleteArmiesOrBuilderList() {
      return deleteArmies_;
    }
    /**
     * <code>repeated .ArmyVO deleteArmies = 1;</code>
     *
     * <pre>
     *Ҫɾ��ľ��
     * </pre>
     */
    public int getDeleteArmiesCount() {
      return deleteArmies_.size();
    }
    /**
     * <code>repeated .ArmyVO deleteArmies = 1;</code>
     *
     * <pre>
     *Ҫɾ��ľ��
     * </pre>
     */
    public com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO getDeleteArmies(int index) {
      return deleteArmies_.get(index);
    }
    /**
     * <code>repeated .ArmyVO deleteArmies = 1;</code>
     *
     * <pre>
     *Ҫɾ��ľ��
     * </pre>
     */
    public com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVOOrBuilder getDeleteArmiesOrBuilder(
        int index) {
      return deleteArmies_.get(index);
    }

    // required .DeleteArmiesReq.DeleteType deleteType = 2;
    public static final int DELETETYPE_FIELD_NUMBER = 2;
    private com.pureland.common.protocal.DeleteArmiesReqProtocal.DeleteArmiesReq.DeleteType deleteType_;
    /**
     * <code>required .DeleteArmiesReq.DeleteType deleteType = 2;</code>
     *
     * <pre>
     *ɾ�������
     * </pre>
     */
    public boolean hasDeleteType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .DeleteArmiesReq.DeleteType deleteType = 2;</code>
     *
     * <pre>
     *ɾ�������
     * </pre>
     */
    public com.pureland.common.protocal.DeleteArmiesReqProtocal.DeleteArmiesReq.DeleteType getDeleteType() {
      return deleteType_;
    }

    private void initFields() {
      deleteArmies_ = java.util.Collections.emptyList();
      deleteType_ = com.pureland.common.protocal.DeleteArmiesReqProtocal.DeleteArmiesReq.DeleteType.Barrack;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasDeleteType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getDeleteArmiesCount(); i++) {
        if (!getDeleteArmies(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < deleteArmies_.size(); i++) {
        output.writeMessage(1, deleteArmies_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(2, deleteType_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < deleteArmies_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, deleteArmies_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, deleteType_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.pureland.common.protocal.DeleteArmiesReqProtocal.DeleteArmiesReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pureland.common.protocal.DeleteArmiesReqProtocal.DeleteArmiesReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pureland.common.protocal.DeleteArmiesReqProtocal.DeleteArmiesReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pureland.common.protocal.DeleteArmiesReqProtocal.DeleteArmiesReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pureland.common.protocal.DeleteArmiesReqProtocal.DeleteArmiesReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.pureland.common.protocal.DeleteArmiesReqProtocal.DeleteArmiesReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.pureland.common.protocal.DeleteArmiesReqProtocal.DeleteArmiesReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.pureland.common.protocal.DeleteArmiesReqProtocal.DeleteArmiesReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.pureland.common.protocal.DeleteArmiesReqProtocal.DeleteArmiesReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.pureland.common.protocal.DeleteArmiesReqProtocal.DeleteArmiesReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.pureland.common.protocal.DeleteArmiesReqProtocal.DeleteArmiesReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DeleteArmiesReq}
     *
     * <pre>
     *�������彨��
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.pureland.common.protocal.DeleteArmiesReqProtocal.DeleteArmiesReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pureland.common.protocal.DeleteArmiesReqProtocal.internal_static_DeleteArmiesReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pureland.common.protocal.DeleteArmiesReqProtocal.internal_static_DeleteArmiesReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pureland.common.protocal.DeleteArmiesReqProtocal.DeleteArmiesReq.class, com.pureland.common.protocal.DeleteArmiesReqProtocal.DeleteArmiesReq.Builder.class);
      }

      // Construct using com.pureland.common.protocal.DeleteArmiesReqProtocal.DeleteArmiesReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDeleteArmiesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (deleteArmiesBuilder_ == null) {
          deleteArmies_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          deleteArmiesBuilder_.clear();
        }
        deleteType_ = com.pureland.common.protocal.DeleteArmiesReqProtocal.DeleteArmiesReq.DeleteType.Barrack;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pureland.common.protocal.DeleteArmiesReqProtocal.internal_static_DeleteArmiesReq_descriptor;
      }

      public com.pureland.common.protocal.DeleteArmiesReqProtocal.DeleteArmiesReq getDefaultInstanceForType() {
        return com.pureland.common.protocal.DeleteArmiesReqProtocal.DeleteArmiesReq.getDefaultInstance();
      }

      public com.pureland.common.protocal.DeleteArmiesReqProtocal.DeleteArmiesReq build() {
        com.pureland.common.protocal.DeleteArmiesReqProtocal.DeleteArmiesReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.pureland.common.protocal.DeleteArmiesReqProtocal.DeleteArmiesReq buildPartial() {
        com.pureland.common.protocal.DeleteArmiesReqProtocal.DeleteArmiesReq result = new com.pureland.common.protocal.DeleteArmiesReqProtocal.DeleteArmiesReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (deleteArmiesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            deleteArmies_ = java.util.Collections.unmodifiableList(deleteArmies_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.deleteArmies_ = deleteArmies_;
        } else {
          result.deleteArmies_ = deleteArmiesBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.deleteType_ = deleteType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pureland.common.protocal.DeleteArmiesReqProtocal.DeleteArmiesReq) {
          return mergeFrom((com.pureland.common.protocal.DeleteArmiesReqProtocal.DeleteArmiesReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.pureland.common.protocal.DeleteArmiesReqProtocal.DeleteArmiesReq other) {
        if (other == com.pureland.common.protocal.DeleteArmiesReqProtocal.DeleteArmiesReq.getDefaultInstance()) return this;
        if (deleteArmiesBuilder_ == null) {
          if (!other.deleteArmies_.isEmpty()) {
            if (deleteArmies_.isEmpty()) {
              deleteArmies_ = other.deleteArmies_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDeleteArmiesIsMutable();
              deleteArmies_.addAll(other.deleteArmies_);
            }
            onChanged();
          }
        } else {
          if (!other.deleteArmies_.isEmpty()) {
            if (deleteArmiesBuilder_.isEmpty()) {
              deleteArmiesBuilder_.dispose();
              deleteArmiesBuilder_ = null;
              deleteArmies_ = other.deleteArmies_;
              bitField0_ = (bitField0_ & ~0x00000001);
              deleteArmiesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDeleteArmiesFieldBuilder() : null;
            } else {
              deleteArmiesBuilder_.addAllMessages(other.deleteArmies_);
            }
          }
        }
        if (other.hasDeleteType()) {
          setDeleteType(other.getDeleteType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDeleteType()) {
          
          return false;
        }
        for (int i = 0; i < getDeleteArmiesCount(); i++) {
          if (!getDeleteArmies(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.pureland.common.protocal.DeleteArmiesReqProtocal.DeleteArmiesReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.pureland.common.protocal.DeleteArmiesReqProtocal.DeleteArmiesReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .ArmyVO deleteArmies = 1;
      private java.util.List<com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO> deleteArmies_ =
        java.util.Collections.emptyList();
      private void ensureDeleteArmiesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          deleteArmies_ = new java.util.ArrayList<com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO>(deleteArmies_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO, com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO.Builder, com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVOOrBuilder> deleteArmiesBuilder_;

      /**
       * <code>repeated .ArmyVO deleteArmies = 1;</code>
       *
       * <pre>
       *Ҫɾ��ľ��
       * </pre>
       */
      public java.util.List<com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO> getDeleteArmiesList() {
        if (deleteArmiesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(deleteArmies_);
        } else {
          return deleteArmiesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ArmyVO deleteArmies = 1;</code>
       *
       * <pre>
       *Ҫɾ��ľ��
       * </pre>
       */
      public int getDeleteArmiesCount() {
        if (deleteArmiesBuilder_ == null) {
          return deleteArmies_.size();
        } else {
          return deleteArmiesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ArmyVO deleteArmies = 1;</code>
       *
       * <pre>
       *Ҫɾ��ľ��
       * </pre>
       */
      public com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO getDeleteArmies(int index) {
        if (deleteArmiesBuilder_ == null) {
          return deleteArmies_.get(index);
        } else {
          return deleteArmiesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ArmyVO deleteArmies = 1;</code>
       *
       * <pre>
       *Ҫɾ��ľ��
       * </pre>
       */
      public Builder setDeleteArmies(
          int index, com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO value) {
        if (deleteArmiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDeleteArmiesIsMutable();
          deleteArmies_.set(index, value);
          onChanged();
        } else {
          deleteArmiesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ArmyVO deleteArmies = 1;</code>
       *
       * <pre>
       *Ҫɾ��ľ��
       * </pre>
       */
      public Builder setDeleteArmies(
          int index, com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO.Builder builderForValue) {
        if (deleteArmiesBuilder_ == null) {
          ensureDeleteArmiesIsMutable();
          deleteArmies_.set(index, builderForValue.build());
          onChanged();
        } else {
          deleteArmiesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ArmyVO deleteArmies = 1;</code>
       *
       * <pre>
       *Ҫɾ��ľ��
       * </pre>
       */
      public Builder addDeleteArmies(com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO value) {
        if (deleteArmiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDeleteArmiesIsMutable();
          deleteArmies_.add(value);
          onChanged();
        } else {
          deleteArmiesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ArmyVO deleteArmies = 1;</code>
       *
       * <pre>
       *Ҫɾ��ľ��
       * </pre>
       */
      public Builder addDeleteArmies(
          int index, com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO value) {
        if (deleteArmiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDeleteArmiesIsMutable();
          deleteArmies_.add(index, value);
          onChanged();
        } else {
          deleteArmiesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ArmyVO deleteArmies = 1;</code>
       *
       * <pre>
       *Ҫɾ��ľ��
       * </pre>
       */
      public Builder addDeleteArmies(
          com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO.Builder builderForValue) {
        if (deleteArmiesBuilder_ == null) {
          ensureDeleteArmiesIsMutable();
          deleteArmies_.add(builderForValue.build());
          onChanged();
        } else {
          deleteArmiesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ArmyVO deleteArmies = 1;</code>
       *
       * <pre>
       *Ҫɾ��ľ��
       * </pre>
       */
      public Builder addDeleteArmies(
          int index, com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO.Builder builderForValue) {
        if (deleteArmiesBuilder_ == null) {
          ensureDeleteArmiesIsMutable();
          deleteArmies_.add(index, builderForValue.build());
          onChanged();
        } else {
          deleteArmiesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ArmyVO deleteArmies = 1;</code>
       *
       * <pre>
       *Ҫɾ��ľ��
       * </pre>
       */
      public Builder addAllDeleteArmies(
          java.lang.Iterable<? extends com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO> values) {
        if (deleteArmiesBuilder_ == null) {
          ensureDeleteArmiesIsMutable();
          super.addAll(values, deleteArmies_);
          onChanged();
        } else {
          deleteArmiesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ArmyVO deleteArmies = 1;</code>
       *
       * <pre>
       *Ҫɾ��ľ��
       * </pre>
       */
      public Builder clearDeleteArmies() {
        if (deleteArmiesBuilder_ == null) {
          deleteArmies_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          deleteArmiesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ArmyVO deleteArmies = 1;</code>
       *
       * <pre>
       *Ҫɾ��ľ��
       * </pre>
       */
      public Builder removeDeleteArmies(int index) {
        if (deleteArmiesBuilder_ == null) {
          ensureDeleteArmiesIsMutable();
          deleteArmies_.remove(index);
          onChanged();
        } else {
          deleteArmiesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ArmyVO deleteArmies = 1;</code>
       *
       * <pre>
       *Ҫɾ��ľ��
       * </pre>
       */
      public com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO.Builder getDeleteArmiesBuilder(
          int index) {
        return getDeleteArmiesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ArmyVO deleteArmies = 1;</code>
       *
       * <pre>
       *Ҫɾ��ľ��
       * </pre>
       */
      public com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVOOrBuilder getDeleteArmiesOrBuilder(
          int index) {
        if (deleteArmiesBuilder_ == null) {
          return deleteArmies_.get(index);  } else {
          return deleteArmiesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ArmyVO deleteArmies = 1;</code>
       *
       * <pre>
       *Ҫɾ��ľ��
       * </pre>
       */
      public java.util.List<? extends com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVOOrBuilder> 
           getDeleteArmiesOrBuilderList() {
        if (deleteArmiesBuilder_ != null) {
          return deleteArmiesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(deleteArmies_);
        }
      }
      /**
       * <code>repeated .ArmyVO deleteArmies = 1;</code>
       *
       * <pre>
       *Ҫɾ��ľ��
       * </pre>
       */
      public com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO.Builder addDeleteArmiesBuilder() {
        return getDeleteArmiesFieldBuilder().addBuilder(
            com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO.getDefaultInstance());
      }
      /**
       * <code>repeated .ArmyVO deleteArmies = 1;</code>
       *
       * <pre>
       *Ҫɾ��ľ��
       * </pre>
       */
      public com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO.Builder addDeleteArmiesBuilder(
          int index) {
        return getDeleteArmiesFieldBuilder().addBuilder(
            index, com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO.getDefaultInstance());
      }
      /**
       * <code>repeated .ArmyVO deleteArmies = 1;</code>
       *
       * <pre>
       *Ҫɾ��ľ��
       * </pre>
       */
      public java.util.List<com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO.Builder> 
           getDeleteArmiesBuilderList() {
        return getDeleteArmiesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO, com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO.Builder, com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVOOrBuilder> 
          getDeleteArmiesFieldBuilder() {
        if (deleteArmiesBuilder_ == null) {
          deleteArmiesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO, com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO.Builder, com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVOOrBuilder>(
                  deleteArmies_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          deleteArmies_ = null;
        }
        return deleteArmiesBuilder_;
      }

      // required .DeleteArmiesReq.DeleteType deleteType = 2;
      private com.pureland.common.protocal.DeleteArmiesReqProtocal.DeleteArmiesReq.DeleteType deleteType_ = com.pureland.common.protocal.DeleteArmiesReqProtocal.DeleteArmiesReq.DeleteType.Barrack;
      /**
       * <code>required .DeleteArmiesReq.DeleteType deleteType = 2;</code>
       *
       * <pre>
       *ɾ�������
       * </pre>
       */
      public boolean hasDeleteType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .DeleteArmiesReq.DeleteType deleteType = 2;</code>
       *
       * <pre>
       *ɾ�������
       * </pre>
       */
      public com.pureland.common.protocal.DeleteArmiesReqProtocal.DeleteArmiesReq.DeleteType getDeleteType() {
        return deleteType_;
      }
      /**
       * <code>required .DeleteArmiesReq.DeleteType deleteType = 2;</code>
       *
       * <pre>
       *ɾ�������
       * </pre>
       */
      public Builder setDeleteType(com.pureland.common.protocal.DeleteArmiesReqProtocal.DeleteArmiesReq.DeleteType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        deleteType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .DeleteArmiesReq.DeleteType deleteType = 2;</code>
       *
       * <pre>
       *ɾ�������
       * </pre>
       */
      public Builder clearDeleteType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        deleteType_ = com.pureland.common.protocal.DeleteArmiesReqProtocal.DeleteArmiesReq.DeleteType.Barrack;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:DeleteArmiesReq)
    }

    static {
      defaultInstance = new DeleteArmiesReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:DeleteArmiesReq)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteArmiesReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DeleteArmiesReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025DeleteArmiesReq.proto\032\014ArmyVO.proto\"\211\001" +
      "\n\017DeleteArmiesReq\022\035\n\014deleteArmies\030\001 \003(\0132" +
      "\007.ArmyVO\022/\n\ndeleteType\030\002 \002(\0162\033.DeleteArm" +
      "iesReq.DeleteType\"&\n\nDeleteType\022\013\n\007Barra" +
      "ck\020\001\022\013\n\007Federal\020\002B7\n\034com.pureland.common" +
      ".protocalB\027DeleteArmiesReqProtocal"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_DeleteArmiesReq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_DeleteArmiesReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_DeleteArmiesReq_descriptor,
              new java.lang.String[] { "DeleteArmies", "DeleteType", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.pureland.common.protocal.vo.ArmyVOProtocal.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
