// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExploreResp.proto

package com.pureland.common.protocal;

public final class ExploreRespProtocal {
  private ExploreRespProtocal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ExploreRespOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .ExploreShipVO exploreShipList = 1;
    /**
     * <code>repeated .ExploreShipVO exploreShipList = 1;</code>
     */
    java.util.List<com.pureland.common.protocal.vo.ExploreShipVOProtocal.ExploreShipVO> 
        getExploreShipListList();
    /**
     * <code>repeated .ExploreShipVO exploreShipList = 1;</code>
     */
    com.pureland.common.protocal.vo.ExploreShipVOProtocal.ExploreShipVO getExploreShipList(int index);
    /**
     * <code>repeated .ExploreShipVO exploreShipList = 1;</code>
     */
    int getExploreShipListCount();
    /**
     * <code>repeated .ExploreShipVO exploreShipList = 1;</code>
     */
    java.util.List<? extends com.pureland.common.protocal.vo.ExploreShipVOProtocal.ExploreShipVOOrBuilder> 
        getExploreShipListOrBuilderList();
    /**
     * <code>repeated .ExploreShipVO exploreShipList = 1;</code>
     */
    com.pureland.common.protocal.vo.ExploreShipVOProtocal.ExploreShipVOOrBuilder getExploreShipListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ExploreResp}
   */
  public static final class ExploreResp extends
      com.google.protobuf.GeneratedMessage
      implements ExploreRespOrBuilder {
    // Use ExploreResp.newBuilder() to construct.
    private ExploreResp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ExploreResp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ExploreResp defaultInstance;
    public static ExploreResp getDefaultInstance() {
      return defaultInstance;
    }

    public ExploreResp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ExploreResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                exploreShipList_ = new java.util.ArrayList<com.pureland.common.protocal.vo.ExploreShipVOProtocal.ExploreShipVO>();
                mutable_bitField0_ |= 0x00000001;
              }
              exploreShipList_.add(input.readMessage(com.pureland.common.protocal.vo.ExploreShipVOProtocal.ExploreShipVO.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          exploreShipList_ = java.util.Collections.unmodifiableList(exploreShipList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pureland.common.protocal.ExploreRespProtocal.internal_static_ExploreResp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pureland.common.protocal.ExploreRespProtocal.internal_static_ExploreResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pureland.common.protocal.ExploreRespProtocal.ExploreResp.class, com.pureland.common.protocal.ExploreRespProtocal.ExploreResp.Builder.class);
    }

    public static com.google.protobuf.Parser<ExploreResp> PARSER =
        new com.google.protobuf.AbstractParser<ExploreResp>() {
      public ExploreResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExploreResp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ExploreResp> getParserForType() {
      return PARSER;
    }

    // repeated .ExploreShipVO exploreShipList = 1;
    public static final int EXPLORESHIPLIST_FIELD_NUMBER = 1;
    private java.util.List<com.pureland.common.protocal.vo.ExploreShipVOProtocal.ExploreShipVO> exploreShipList_;
    /**
     * <code>repeated .ExploreShipVO exploreShipList = 1;</code>
     */
    public java.util.List<com.pureland.common.protocal.vo.ExploreShipVOProtocal.ExploreShipVO> getExploreShipListList() {
      return exploreShipList_;
    }
    /**
     * <code>repeated .ExploreShipVO exploreShipList = 1;</code>
     */
    public java.util.List<? extends com.pureland.common.protocal.vo.ExploreShipVOProtocal.ExploreShipVOOrBuilder> 
        getExploreShipListOrBuilderList() {
      return exploreShipList_;
    }
    /**
     * <code>repeated .ExploreShipVO exploreShipList = 1;</code>
     */
    public int getExploreShipListCount() {
      return exploreShipList_.size();
    }
    /**
     * <code>repeated .ExploreShipVO exploreShipList = 1;</code>
     */
    public com.pureland.common.protocal.vo.ExploreShipVOProtocal.ExploreShipVO getExploreShipList(int index) {
      return exploreShipList_.get(index);
    }
    /**
     * <code>repeated .ExploreShipVO exploreShipList = 1;</code>
     */
    public com.pureland.common.protocal.vo.ExploreShipVOProtocal.ExploreShipVOOrBuilder getExploreShipListOrBuilder(
        int index) {
      return exploreShipList_.get(index);
    }

    private void initFields() {
      exploreShipList_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getExploreShipListCount(); i++) {
        if (!getExploreShipList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < exploreShipList_.size(); i++) {
        output.writeMessage(1, exploreShipList_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < exploreShipList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, exploreShipList_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.pureland.common.protocal.ExploreRespProtocal.ExploreResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pureland.common.protocal.ExploreRespProtocal.ExploreResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pureland.common.protocal.ExploreRespProtocal.ExploreResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pureland.common.protocal.ExploreRespProtocal.ExploreResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pureland.common.protocal.ExploreRespProtocal.ExploreResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.pureland.common.protocal.ExploreRespProtocal.ExploreResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.pureland.common.protocal.ExploreRespProtocal.ExploreResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.pureland.common.protocal.ExploreRespProtocal.ExploreResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.pureland.common.protocal.ExploreRespProtocal.ExploreResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.pureland.common.protocal.ExploreRespProtocal.ExploreResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.pureland.common.protocal.ExploreRespProtocal.ExploreResp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ExploreResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.pureland.common.protocal.ExploreRespProtocal.ExploreRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pureland.common.protocal.ExploreRespProtocal.internal_static_ExploreResp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pureland.common.protocal.ExploreRespProtocal.internal_static_ExploreResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pureland.common.protocal.ExploreRespProtocal.ExploreResp.class, com.pureland.common.protocal.ExploreRespProtocal.ExploreResp.Builder.class);
      }

      // Construct using com.pureland.common.protocal.ExploreRespProtocal.ExploreResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getExploreShipListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (exploreShipListBuilder_ == null) {
          exploreShipList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          exploreShipListBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pureland.common.protocal.ExploreRespProtocal.internal_static_ExploreResp_descriptor;
      }

      public com.pureland.common.protocal.ExploreRespProtocal.ExploreResp getDefaultInstanceForType() {
        return com.pureland.common.protocal.ExploreRespProtocal.ExploreResp.getDefaultInstance();
      }

      public com.pureland.common.protocal.ExploreRespProtocal.ExploreResp build() {
        com.pureland.common.protocal.ExploreRespProtocal.ExploreResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.pureland.common.protocal.ExploreRespProtocal.ExploreResp buildPartial() {
        com.pureland.common.protocal.ExploreRespProtocal.ExploreResp result = new com.pureland.common.protocal.ExploreRespProtocal.ExploreResp(this);
        int from_bitField0_ = bitField0_;
        if (exploreShipListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            exploreShipList_ = java.util.Collections.unmodifiableList(exploreShipList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.exploreShipList_ = exploreShipList_;
        } else {
          result.exploreShipList_ = exploreShipListBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pureland.common.protocal.ExploreRespProtocal.ExploreResp) {
          return mergeFrom((com.pureland.common.protocal.ExploreRespProtocal.ExploreResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.pureland.common.protocal.ExploreRespProtocal.ExploreResp other) {
        if (other == com.pureland.common.protocal.ExploreRespProtocal.ExploreResp.getDefaultInstance()) return this;
        if (exploreShipListBuilder_ == null) {
          if (!other.exploreShipList_.isEmpty()) {
            if (exploreShipList_.isEmpty()) {
              exploreShipList_ = other.exploreShipList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureExploreShipListIsMutable();
              exploreShipList_.addAll(other.exploreShipList_);
            }
            onChanged();
          }
        } else {
          if (!other.exploreShipList_.isEmpty()) {
            if (exploreShipListBuilder_.isEmpty()) {
              exploreShipListBuilder_.dispose();
              exploreShipListBuilder_ = null;
              exploreShipList_ = other.exploreShipList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              exploreShipListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getExploreShipListFieldBuilder() : null;
            } else {
              exploreShipListBuilder_.addAllMessages(other.exploreShipList_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getExploreShipListCount(); i++) {
          if (!getExploreShipList(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.pureland.common.protocal.ExploreRespProtocal.ExploreResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.pureland.common.protocal.ExploreRespProtocal.ExploreResp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .ExploreShipVO exploreShipList = 1;
      private java.util.List<com.pureland.common.protocal.vo.ExploreShipVOProtocal.ExploreShipVO> exploreShipList_ =
        java.util.Collections.emptyList();
      private void ensureExploreShipListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          exploreShipList_ = new java.util.ArrayList<com.pureland.common.protocal.vo.ExploreShipVOProtocal.ExploreShipVO>(exploreShipList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.pureland.common.protocal.vo.ExploreShipVOProtocal.ExploreShipVO, com.pureland.common.protocal.vo.ExploreShipVOProtocal.ExploreShipVO.Builder, com.pureland.common.protocal.vo.ExploreShipVOProtocal.ExploreShipVOOrBuilder> exploreShipListBuilder_;

      /**
       * <code>repeated .ExploreShipVO exploreShipList = 1;</code>
       */
      public java.util.List<com.pureland.common.protocal.vo.ExploreShipVOProtocal.ExploreShipVO> getExploreShipListList() {
        if (exploreShipListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(exploreShipList_);
        } else {
          return exploreShipListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ExploreShipVO exploreShipList = 1;</code>
       */
      public int getExploreShipListCount() {
        if (exploreShipListBuilder_ == null) {
          return exploreShipList_.size();
        } else {
          return exploreShipListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ExploreShipVO exploreShipList = 1;</code>
       */
      public com.pureland.common.protocal.vo.ExploreShipVOProtocal.ExploreShipVO getExploreShipList(int index) {
        if (exploreShipListBuilder_ == null) {
          return exploreShipList_.get(index);
        } else {
          return exploreShipListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ExploreShipVO exploreShipList = 1;</code>
       */
      public Builder setExploreShipList(
          int index, com.pureland.common.protocal.vo.ExploreShipVOProtocal.ExploreShipVO value) {
        if (exploreShipListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExploreShipListIsMutable();
          exploreShipList_.set(index, value);
          onChanged();
        } else {
          exploreShipListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ExploreShipVO exploreShipList = 1;</code>
       */
      public Builder setExploreShipList(
          int index, com.pureland.common.protocal.vo.ExploreShipVOProtocal.ExploreShipVO.Builder builderForValue) {
        if (exploreShipListBuilder_ == null) {
          ensureExploreShipListIsMutable();
          exploreShipList_.set(index, builderForValue.build());
          onChanged();
        } else {
          exploreShipListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ExploreShipVO exploreShipList = 1;</code>
       */
      public Builder addExploreShipList(com.pureland.common.protocal.vo.ExploreShipVOProtocal.ExploreShipVO value) {
        if (exploreShipListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExploreShipListIsMutable();
          exploreShipList_.add(value);
          onChanged();
        } else {
          exploreShipListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ExploreShipVO exploreShipList = 1;</code>
       */
      public Builder addExploreShipList(
          int index, com.pureland.common.protocal.vo.ExploreShipVOProtocal.ExploreShipVO value) {
        if (exploreShipListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExploreShipListIsMutable();
          exploreShipList_.add(index, value);
          onChanged();
        } else {
          exploreShipListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ExploreShipVO exploreShipList = 1;</code>
       */
      public Builder addExploreShipList(
          com.pureland.common.protocal.vo.ExploreShipVOProtocal.ExploreShipVO.Builder builderForValue) {
        if (exploreShipListBuilder_ == null) {
          ensureExploreShipListIsMutable();
          exploreShipList_.add(builderForValue.build());
          onChanged();
        } else {
          exploreShipListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ExploreShipVO exploreShipList = 1;</code>
       */
      public Builder addExploreShipList(
          int index, com.pureland.common.protocal.vo.ExploreShipVOProtocal.ExploreShipVO.Builder builderForValue) {
        if (exploreShipListBuilder_ == null) {
          ensureExploreShipListIsMutable();
          exploreShipList_.add(index, builderForValue.build());
          onChanged();
        } else {
          exploreShipListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ExploreShipVO exploreShipList = 1;</code>
       */
      public Builder addAllExploreShipList(
          java.lang.Iterable<? extends com.pureland.common.protocal.vo.ExploreShipVOProtocal.ExploreShipVO> values) {
        if (exploreShipListBuilder_ == null) {
          ensureExploreShipListIsMutable();
          super.addAll(values, exploreShipList_);
          onChanged();
        } else {
          exploreShipListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ExploreShipVO exploreShipList = 1;</code>
       */
      public Builder clearExploreShipList() {
        if (exploreShipListBuilder_ == null) {
          exploreShipList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          exploreShipListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ExploreShipVO exploreShipList = 1;</code>
       */
      public Builder removeExploreShipList(int index) {
        if (exploreShipListBuilder_ == null) {
          ensureExploreShipListIsMutable();
          exploreShipList_.remove(index);
          onChanged();
        } else {
          exploreShipListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ExploreShipVO exploreShipList = 1;</code>
       */
      public com.pureland.common.protocal.vo.ExploreShipVOProtocal.ExploreShipVO.Builder getExploreShipListBuilder(
          int index) {
        return getExploreShipListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ExploreShipVO exploreShipList = 1;</code>
       */
      public com.pureland.common.protocal.vo.ExploreShipVOProtocal.ExploreShipVOOrBuilder getExploreShipListOrBuilder(
          int index) {
        if (exploreShipListBuilder_ == null) {
          return exploreShipList_.get(index);  } else {
          return exploreShipListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ExploreShipVO exploreShipList = 1;</code>
       */
      public java.util.List<? extends com.pureland.common.protocal.vo.ExploreShipVOProtocal.ExploreShipVOOrBuilder> 
           getExploreShipListOrBuilderList() {
        if (exploreShipListBuilder_ != null) {
          return exploreShipListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(exploreShipList_);
        }
      }
      /**
       * <code>repeated .ExploreShipVO exploreShipList = 1;</code>
       */
      public com.pureland.common.protocal.vo.ExploreShipVOProtocal.ExploreShipVO.Builder addExploreShipListBuilder() {
        return getExploreShipListFieldBuilder().addBuilder(
            com.pureland.common.protocal.vo.ExploreShipVOProtocal.ExploreShipVO.getDefaultInstance());
      }
      /**
       * <code>repeated .ExploreShipVO exploreShipList = 1;</code>
       */
      public com.pureland.common.protocal.vo.ExploreShipVOProtocal.ExploreShipVO.Builder addExploreShipListBuilder(
          int index) {
        return getExploreShipListFieldBuilder().addBuilder(
            index, com.pureland.common.protocal.vo.ExploreShipVOProtocal.ExploreShipVO.getDefaultInstance());
      }
      /**
       * <code>repeated .ExploreShipVO exploreShipList = 1;</code>
       */
      public java.util.List<com.pureland.common.protocal.vo.ExploreShipVOProtocal.ExploreShipVO.Builder> 
           getExploreShipListBuilderList() {
        return getExploreShipListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.pureland.common.protocal.vo.ExploreShipVOProtocal.ExploreShipVO, com.pureland.common.protocal.vo.ExploreShipVOProtocal.ExploreShipVO.Builder, com.pureland.common.protocal.vo.ExploreShipVOProtocal.ExploreShipVOOrBuilder> 
          getExploreShipListFieldBuilder() {
        if (exploreShipListBuilder_ == null) {
          exploreShipListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.pureland.common.protocal.vo.ExploreShipVOProtocal.ExploreShipVO, com.pureland.common.protocal.vo.ExploreShipVOProtocal.ExploreShipVO.Builder, com.pureland.common.protocal.vo.ExploreShipVOProtocal.ExploreShipVOOrBuilder>(
                  exploreShipList_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          exploreShipList_ = null;
        }
        return exploreShipListBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ExploreResp)
    }

    static {
      defaultInstance = new ExploreResp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ExploreResp)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ExploreResp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ExploreResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ExploreResp.proto\032\023ExploreShipVO.proto" +
      "\"6\n\013ExploreResp\022\'\n\017exploreShipList\030\001 \003(\013" +
      "2\016.ExploreShipVOB3\n\034com.pureland.common." +
      "protocalB\023ExploreRespProtocal"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ExploreResp_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ExploreResp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ExploreResp_descriptor,
              new java.lang.String[] { "ExploreShipList", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.pureland.common.protocal.vo.ExploreShipVOProtocal.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
