// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FightSearchReq.proto

package com.pureland.common.protocal;

public final class FightSearchReqProtocal {
  private FightSearchReqProtocal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FightSearchReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .FightSearchReq.SearchType searchType = 1;
    /**
     * <code>required .FightSearchReq.SearchType searchType = 1;</code>
     *
     * <pre>
     *战斗搜索类型
     * </pre>
     */
    boolean hasSearchType();
    /**
     * <code>required .FightSearchReq.SearchType searchType = 1;</code>
     *
     * <pre>
     *战斗搜索类型
     * </pre>
     */
    com.pureland.common.protocal.FightSearchReqProtocal.FightSearchReq.SearchType getSearchType();
  }
  /**
   * Protobuf type {@code FightSearchReq}
   */
  public static final class FightSearchReq extends
      com.google.protobuf.GeneratedMessage
      implements FightSearchReqOrBuilder {
    // Use FightSearchReq.newBuilder() to construct.
    private FightSearchReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FightSearchReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FightSearchReq defaultInstance;
    public static FightSearchReq getDefaultInstance() {
      return defaultInstance;
    }

    public FightSearchReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FightSearchReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.pureland.common.protocal.FightSearchReqProtocal.FightSearchReq.SearchType value = com.pureland.common.protocal.FightSearchReqProtocal.FightSearchReq.SearchType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                searchType_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pureland.common.protocal.FightSearchReqProtocal.internal_static_FightSearchReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pureland.common.protocal.FightSearchReqProtocal.internal_static_FightSearchReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pureland.common.protocal.FightSearchReqProtocal.FightSearchReq.class, com.pureland.common.protocal.FightSearchReqProtocal.FightSearchReq.Builder.class);
    }

    public static com.google.protobuf.Parser<FightSearchReq> PARSER =
        new com.google.protobuf.AbstractParser<FightSearchReq>() {
      public FightSearchReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FightSearchReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FightSearchReq> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code FightSearchReq.SearchType}
     */
    public enum SearchType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>PVE = 1;</code>
       *
       * <pre>
       *本地NPC
       * </pre>
       */
      PVE(0, 1),
      /**
       * <code>PVP_NORMAL = 2;</code>
       *
       * <pre>
       *玩家PVP普通搜索
       * </pre>
       */
      PVP_NORMAL(1, 2),
      /**
       * <code>PVP_HIGH = 3;</code>
       *
       * <pre>
       *玩家PVP高级搜索
       * </pre>
       */
      PVP_HIGH(2, 3),
      ;

      /**
       * <code>PVE = 1;</code>
       *
       * <pre>
       *本地NPC
       * </pre>
       */
      public static final int PVE_VALUE = 1;
      /**
       * <code>PVP_NORMAL = 2;</code>
       *
       * <pre>
       *玩家PVP普通搜索
       * </pre>
       */
      public static final int PVP_NORMAL_VALUE = 2;
      /**
       * <code>PVP_HIGH = 3;</code>
       *
       * <pre>
       *玩家PVP高级搜索
       * </pre>
       */
      public static final int PVP_HIGH_VALUE = 3;


      public final int getNumber() { return value; }

      public static SearchType valueOf(int value) {
        switch (value) {
          case 1: return PVE;
          case 2: return PVP_NORMAL;
          case 3: return PVP_HIGH;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<SearchType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<SearchType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<SearchType>() {
              public SearchType findValueByNumber(int number) {
                return SearchType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.pureland.common.protocal.FightSearchReqProtocal.FightSearchReq.getDescriptor().getEnumTypes().get(0);
      }

      private static final SearchType[] VALUES = values();

      public static SearchType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private SearchType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:FightSearchReq.SearchType)
    }

    private int bitField0_;
    // required .FightSearchReq.SearchType searchType = 1;
    public static final int SEARCHTYPE_FIELD_NUMBER = 1;
    private com.pureland.common.protocal.FightSearchReqProtocal.FightSearchReq.SearchType searchType_;
    /**
     * <code>required .FightSearchReq.SearchType searchType = 1;</code>
     *
     * <pre>
     *战斗搜索类型
     * </pre>
     */
    public boolean hasSearchType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .FightSearchReq.SearchType searchType = 1;</code>
     *
     * <pre>
     *战斗搜索类型
     * </pre>
     */
    public com.pureland.common.protocal.FightSearchReqProtocal.FightSearchReq.SearchType getSearchType() {
      return searchType_;
    }

    private void initFields() {
      searchType_ = com.pureland.common.protocal.FightSearchReqProtocal.FightSearchReq.SearchType.PVE;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSearchType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, searchType_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, searchType_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.pureland.common.protocal.FightSearchReqProtocal.FightSearchReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pureland.common.protocal.FightSearchReqProtocal.FightSearchReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pureland.common.protocal.FightSearchReqProtocal.FightSearchReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pureland.common.protocal.FightSearchReqProtocal.FightSearchReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pureland.common.protocal.FightSearchReqProtocal.FightSearchReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.pureland.common.protocal.FightSearchReqProtocal.FightSearchReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.pureland.common.protocal.FightSearchReqProtocal.FightSearchReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.pureland.common.protocal.FightSearchReqProtocal.FightSearchReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.pureland.common.protocal.FightSearchReqProtocal.FightSearchReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.pureland.common.protocal.FightSearchReqProtocal.FightSearchReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.pureland.common.protocal.FightSearchReqProtocal.FightSearchReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FightSearchReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.pureland.common.protocal.FightSearchReqProtocal.FightSearchReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pureland.common.protocal.FightSearchReqProtocal.internal_static_FightSearchReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pureland.common.protocal.FightSearchReqProtocal.internal_static_FightSearchReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pureland.common.protocal.FightSearchReqProtocal.FightSearchReq.class, com.pureland.common.protocal.FightSearchReqProtocal.FightSearchReq.Builder.class);
      }

      // Construct using com.pureland.common.protocal.FightSearchReqProtocal.FightSearchReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        searchType_ = com.pureland.common.protocal.FightSearchReqProtocal.FightSearchReq.SearchType.PVE;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pureland.common.protocal.FightSearchReqProtocal.internal_static_FightSearchReq_descriptor;
      }

      public com.pureland.common.protocal.FightSearchReqProtocal.FightSearchReq getDefaultInstanceForType() {
        return com.pureland.common.protocal.FightSearchReqProtocal.FightSearchReq.getDefaultInstance();
      }

      public com.pureland.common.protocal.FightSearchReqProtocal.FightSearchReq build() {
        com.pureland.common.protocal.FightSearchReqProtocal.FightSearchReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.pureland.common.protocal.FightSearchReqProtocal.FightSearchReq buildPartial() {
        com.pureland.common.protocal.FightSearchReqProtocal.FightSearchReq result = new com.pureland.common.protocal.FightSearchReqProtocal.FightSearchReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.searchType_ = searchType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pureland.common.protocal.FightSearchReqProtocal.FightSearchReq) {
          return mergeFrom((com.pureland.common.protocal.FightSearchReqProtocal.FightSearchReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.pureland.common.protocal.FightSearchReqProtocal.FightSearchReq other) {
        if (other == com.pureland.common.protocal.FightSearchReqProtocal.FightSearchReq.getDefaultInstance()) return this;
        if (other.hasSearchType()) {
          setSearchType(other.getSearchType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSearchType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.pureland.common.protocal.FightSearchReqProtocal.FightSearchReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.pureland.common.protocal.FightSearchReqProtocal.FightSearchReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .FightSearchReq.SearchType searchType = 1;
      private com.pureland.common.protocal.FightSearchReqProtocal.FightSearchReq.SearchType searchType_ = com.pureland.common.protocal.FightSearchReqProtocal.FightSearchReq.SearchType.PVE;
      /**
       * <code>required .FightSearchReq.SearchType searchType = 1;</code>
       *
       * <pre>
       *战斗搜索类型
       * </pre>
       */
      public boolean hasSearchType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .FightSearchReq.SearchType searchType = 1;</code>
       *
       * <pre>
       *战斗搜索类型
       * </pre>
       */
      public com.pureland.common.protocal.FightSearchReqProtocal.FightSearchReq.SearchType getSearchType() {
        return searchType_;
      }
      /**
       * <code>required .FightSearchReq.SearchType searchType = 1;</code>
       *
       * <pre>
       *战斗搜索类型
       * </pre>
       */
      public Builder setSearchType(com.pureland.common.protocal.FightSearchReqProtocal.FightSearchReq.SearchType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        searchType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .FightSearchReq.SearchType searchType = 1;</code>
       *
       * <pre>
       *战斗搜索类型
       * </pre>
       */
      public Builder clearSearchType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        searchType_ = com.pureland.common.protocal.FightSearchReqProtocal.FightSearchReq.SearchType.PVE;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:FightSearchReq)
    }

    static {
      defaultInstance = new FightSearchReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:FightSearchReq)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_FightSearchReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FightSearchReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024FightSearchReq.proto\"u\n\016FightSearchReq" +
      "\022.\n\nsearchType\030\001 \002(\0162\032.FightSearchReq.Se" +
      "archType\"3\n\nSearchType\022\007\n\003PVE\020\001\022\016\n\nPVP_N" +
      "ORMAL\020\002\022\014\n\010PVP_HIGH\020\003B6\n\034com.pureland.co" +
      "mmon.protocalB\026FightSearchReqProtocal"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_FightSearchReq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_FightSearchReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_FightSearchReq_descriptor,
              new java.lang.String[] { "SearchType", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
