// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DonateArmyVO.proto

package com.pureland.common.protocal.vo;

public final class DonateArmyVOProtocal {
  private DonateArmyVOProtocal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DonateArmyVOOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 playerid = 1;
    /**
     * <code>optional int64 playerid = 1;</code>
     */
    boolean hasPlayerid();
    /**
     * <code>optional int64 playerid = 1;</code>
     */
    long getPlayerid();

    // repeated .ArmyVO armyVOs = 2;
    /**
     * <code>repeated .ArmyVO armyVOs = 2;</code>
     */
    java.util.List<com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO> 
        getArmyVOsList();
    /**
     * <code>repeated .ArmyVO armyVOs = 2;</code>
     */
    com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO getArmyVOs(int index);
    /**
     * <code>repeated .ArmyVO armyVOs = 2;</code>
     */
    int getArmyVOsCount();
    /**
     * <code>repeated .ArmyVO armyVOs = 2;</code>
     */
    java.util.List<? extends com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVOOrBuilder> 
        getArmyVOsOrBuilderList();
    /**
     * <code>repeated .ArmyVO armyVOs = 2;</code>
     */
    com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVOOrBuilder getArmyVOsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code DonateArmyVO}
   */
  public static final class DonateArmyVO extends
      com.google.protobuf.GeneratedMessage
      implements DonateArmyVOOrBuilder {
    // Use DonateArmyVO.newBuilder() to construct.
    private DonateArmyVO(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DonateArmyVO(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DonateArmyVO defaultInstance;
    public static DonateArmyVO getDefaultInstance() {
      return defaultInstance;
    }

    public DonateArmyVO getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DonateArmyVO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              playerid_ = input.readInt64();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                armyVOs_ = new java.util.ArrayList<com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO>();
                mutable_bitField0_ |= 0x00000002;
              }
              armyVOs_.add(input.readMessage(com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          armyVOs_ = java.util.Collections.unmodifiableList(armyVOs_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pureland.common.protocal.vo.DonateArmyVOProtocal.internal_static_DonateArmyVO_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pureland.common.protocal.vo.DonateArmyVOProtocal.internal_static_DonateArmyVO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pureland.common.protocal.vo.DonateArmyVOProtocal.DonateArmyVO.class, com.pureland.common.protocal.vo.DonateArmyVOProtocal.DonateArmyVO.Builder.class);
    }

    public static com.google.protobuf.Parser<DonateArmyVO> PARSER =
        new com.google.protobuf.AbstractParser<DonateArmyVO>() {
      public DonateArmyVO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DonateArmyVO(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DonateArmyVO> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 playerid = 1;
    public static final int PLAYERID_FIELD_NUMBER = 1;
    private long playerid_;
    /**
     * <code>optional int64 playerid = 1;</code>
     */
    public boolean hasPlayerid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 playerid = 1;</code>
     */
    public long getPlayerid() {
      return playerid_;
    }

    // repeated .ArmyVO armyVOs = 2;
    public static final int ARMYVOS_FIELD_NUMBER = 2;
    private java.util.List<com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO> armyVOs_;
    /**
     * <code>repeated .ArmyVO armyVOs = 2;</code>
     */
    public java.util.List<com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO> getArmyVOsList() {
      return armyVOs_;
    }
    /**
     * <code>repeated .ArmyVO armyVOs = 2;</code>
     */
    public java.util.List<? extends com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVOOrBuilder> 
        getArmyVOsOrBuilderList() {
      return armyVOs_;
    }
    /**
     * <code>repeated .ArmyVO armyVOs = 2;</code>
     */
    public int getArmyVOsCount() {
      return armyVOs_.size();
    }
    /**
     * <code>repeated .ArmyVO armyVOs = 2;</code>
     */
    public com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO getArmyVOs(int index) {
      return armyVOs_.get(index);
    }
    /**
     * <code>repeated .ArmyVO armyVOs = 2;</code>
     */
    public com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVOOrBuilder getArmyVOsOrBuilder(
        int index) {
      return armyVOs_.get(index);
    }

    private void initFields() {
      playerid_ = 0L;
      armyVOs_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getArmyVOsCount(); i++) {
        if (!getArmyVOs(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, playerid_);
      }
      for (int i = 0; i < armyVOs_.size(); i++) {
        output.writeMessage(2, armyVOs_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, playerid_);
      }
      for (int i = 0; i < armyVOs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, armyVOs_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.pureland.common.protocal.vo.DonateArmyVOProtocal.DonateArmyVO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pureland.common.protocal.vo.DonateArmyVOProtocal.DonateArmyVO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pureland.common.protocal.vo.DonateArmyVOProtocal.DonateArmyVO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pureland.common.protocal.vo.DonateArmyVOProtocal.DonateArmyVO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pureland.common.protocal.vo.DonateArmyVOProtocal.DonateArmyVO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.pureland.common.protocal.vo.DonateArmyVOProtocal.DonateArmyVO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.pureland.common.protocal.vo.DonateArmyVOProtocal.DonateArmyVO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.pureland.common.protocal.vo.DonateArmyVOProtocal.DonateArmyVO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.pureland.common.protocal.vo.DonateArmyVOProtocal.DonateArmyVO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.pureland.common.protocal.vo.DonateArmyVOProtocal.DonateArmyVO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.pureland.common.protocal.vo.DonateArmyVOProtocal.DonateArmyVO prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DonateArmyVO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.pureland.common.protocal.vo.DonateArmyVOProtocal.DonateArmyVOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pureland.common.protocal.vo.DonateArmyVOProtocal.internal_static_DonateArmyVO_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pureland.common.protocal.vo.DonateArmyVOProtocal.internal_static_DonateArmyVO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pureland.common.protocal.vo.DonateArmyVOProtocal.DonateArmyVO.class, com.pureland.common.protocal.vo.DonateArmyVOProtocal.DonateArmyVO.Builder.class);
      }

      // Construct using com.pureland.common.protocal.vo.DonateArmyVOProtocal.DonateArmyVO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getArmyVOsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        playerid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (armyVOsBuilder_ == null) {
          armyVOs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          armyVOsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pureland.common.protocal.vo.DonateArmyVOProtocal.internal_static_DonateArmyVO_descriptor;
      }

      public com.pureland.common.protocal.vo.DonateArmyVOProtocal.DonateArmyVO getDefaultInstanceForType() {
        return com.pureland.common.protocal.vo.DonateArmyVOProtocal.DonateArmyVO.getDefaultInstance();
      }

      public com.pureland.common.protocal.vo.DonateArmyVOProtocal.DonateArmyVO build() {
        com.pureland.common.protocal.vo.DonateArmyVOProtocal.DonateArmyVO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.pureland.common.protocal.vo.DonateArmyVOProtocal.DonateArmyVO buildPartial() {
        com.pureland.common.protocal.vo.DonateArmyVOProtocal.DonateArmyVO result = new com.pureland.common.protocal.vo.DonateArmyVOProtocal.DonateArmyVO(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.playerid_ = playerid_;
        if (armyVOsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            armyVOs_ = java.util.Collections.unmodifiableList(armyVOs_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.armyVOs_ = armyVOs_;
        } else {
          result.armyVOs_ = armyVOsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pureland.common.protocal.vo.DonateArmyVOProtocal.DonateArmyVO) {
          return mergeFrom((com.pureland.common.protocal.vo.DonateArmyVOProtocal.DonateArmyVO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.pureland.common.protocal.vo.DonateArmyVOProtocal.DonateArmyVO other) {
        if (other == com.pureland.common.protocal.vo.DonateArmyVOProtocal.DonateArmyVO.getDefaultInstance()) return this;
        if (other.hasPlayerid()) {
          setPlayerid(other.getPlayerid());
        }
        if (armyVOsBuilder_ == null) {
          if (!other.armyVOs_.isEmpty()) {
            if (armyVOs_.isEmpty()) {
              armyVOs_ = other.armyVOs_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureArmyVOsIsMutable();
              armyVOs_.addAll(other.armyVOs_);
            }
            onChanged();
          }
        } else {
          if (!other.armyVOs_.isEmpty()) {
            if (armyVOsBuilder_.isEmpty()) {
              armyVOsBuilder_.dispose();
              armyVOsBuilder_ = null;
              armyVOs_ = other.armyVOs_;
              bitField0_ = (bitField0_ & ~0x00000002);
              armyVOsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getArmyVOsFieldBuilder() : null;
            } else {
              armyVOsBuilder_.addAllMessages(other.armyVOs_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getArmyVOsCount(); i++) {
          if (!getArmyVOs(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.pureland.common.protocal.vo.DonateArmyVOProtocal.DonateArmyVO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.pureland.common.protocal.vo.DonateArmyVOProtocal.DonateArmyVO) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 playerid = 1;
      private long playerid_ ;
      /**
       * <code>optional int64 playerid = 1;</code>
       */
      public boolean hasPlayerid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 playerid = 1;</code>
       */
      public long getPlayerid() {
        return playerid_;
      }
      /**
       * <code>optional int64 playerid = 1;</code>
       */
      public Builder setPlayerid(long value) {
        bitField0_ |= 0x00000001;
        playerid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 playerid = 1;</code>
       */
      public Builder clearPlayerid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        playerid_ = 0L;
        onChanged();
        return this;
      }

      // repeated .ArmyVO armyVOs = 2;
      private java.util.List<com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO> armyVOs_ =
        java.util.Collections.emptyList();
      private void ensureArmyVOsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          armyVOs_ = new java.util.ArrayList<com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO>(armyVOs_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO, com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO.Builder, com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVOOrBuilder> armyVOsBuilder_;

      /**
       * <code>repeated .ArmyVO armyVOs = 2;</code>
       */
      public java.util.List<com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO> getArmyVOsList() {
        if (armyVOsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(armyVOs_);
        } else {
          return armyVOsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ArmyVO armyVOs = 2;</code>
       */
      public int getArmyVOsCount() {
        if (armyVOsBuilder_ == null) {
          return armyVOs_.size();
        } else {
          return armyVOsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ArmyVO armyVOs = 2;</code>
       */
      public com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO getArmyVOs(int index) {
        if (armyVOsBuilder_ == null) {
          return armyVOs_.get(index);
        } else {
          return armyVOsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ArmyVO armyVOs = 2;</code>
       */
      public Builder setArmyVOs(
          int index, com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO value) {
        if (armyVOsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArmyVOsIsMutable();
          armyVOs_.set(index, value);
          onChanged();
        } else {
          armyVOsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ArmyVO armyVOs = 2;</code>
       */
      public Builder setArmyVOs(
          int index, com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO.Builder builderForValue) {
        if (armyVOsBuilder_ == null) {
          ensureArmyVOsIsMutable();
          armyVOs_.set(index, builderForValue.build());
          onChanged();
        } else {
          armyVOsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ArmyVO armyVOs = 2;</code>
       */
      public Builder addArmyVOs(com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO value) {
        if (armyVOsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArmyVOsIsMutable();
          armyVOs_.add(value);
          onChanged();
        } else {
          armyVOsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ArmyVO armyVOs = 2;</code>
       */
      public Builder addArmyVOs(
          int index, com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO value) {
        if (armyVOsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArmyVOsIsMutable();
          armyVOs_.add(index, value);
          onChanged();
        } else {
          armyVOsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ArmyVO armyVOs = 2;</code>
       */
      public Builder addArmyVOs(
          com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO.Builder builderForValue) {
        if (armyVOsBuilder_ == null) {
          ensureArmyVOsIsMutable();
          armyVOs_.add(builderForValue.build());
          onChanged();
        } else {
          armyVOsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ArmyVO armyVOs = 2;</code>
       */
      public Builder addArmyVOs(
          int index, com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO.Builder builderForValue) {
        if (armyVOsBuilder_ == null) {
          ensureArmyVOsIsMutable();
          armyVOs_.add(index, builderForValue.build());
          onChanged();
        } else {
          armyVOsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ArmyVO armyVOs = 2;</code>
       */
      public Builder addAllArmyVOs(
          java.lang.Iterable<? extends com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO> values) {
        if (armyVOsBuilder_ == null) {
          ensureArmyVOsIsMutable();
          super.addAll(values, armyVOs_);
          onChanged();
        } else {
          armyVOsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ArmyVO armyVOs = 2;</code>
       */
      public Builder clearArmyVOs() {
        if (armyVOsBuilder_ == null) {
          armyVOs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          armyVOsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ArmyVO armyVOs = 2;</code>
       */
      public Builder removeArmyVOs(int index) {
        if (armyVOsBuilder_ == null) {
          ensureArmyVOsIsMutable();
          armyVOs_.remove(index);
          onChanged();
        } else {
          armyVOsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ArmyVO armyVOs = 2;</code>
       */
      public com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO.Builder getArmyVOsBuilder(
          int index) {
        return getArmyVOsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ArmyVO armyVOs = 2;</code>
       */
      public com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVOOrBuilder getArmyVOsOrBuilder(
          int index) {
        if (armyVOsBuilder_ == null) {
          return armyVOs_.get(index);  } else {
          return armyVOsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ArmyVO armyVOs = 2;</code>
       */
      public java.util.List<? extends com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVOOrBuilder> 
           getArmyVOsOrBuilderList() {
        if (armyVOsBuilder_ != null) {
          return armyVOsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(armyVOs_);
        }
      }
      /**
       * <code>repeated .ArmyVO armyVOs = 2;</code>
       */
      public com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO.Builder addArmyVOsBuilder() {
        return getArmyVOsFieldBuilder().addBuilder(
            com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO.getDefaultInstance());
      }
      /**
       * <code>repeated .ArmyVO armyVOs = 2;</code>
       */
      public com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO.Builder addArmyVOsBuilder(
          int index) {
        return getArmyVOsFieldBuilder().addBuilder(
            index, com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO.getDefaultInstance());
      }
      /**
       * <code>repeated .ArmyVO armyVOs = 2;</code>
       */
      public java.util.List<com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO.Builder> 
           getArmyVOsBuilderList() {
        return getArmyVOsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO, com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO.Builder, com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVOOrBuilder> 
          getArmyVOsFieldBuilder() {
        if (armyVOsBuilder_ == null) {
          armyVOsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO, com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVO.Builder, com.pureland.common.protocal.vo.ArmyVOProtocal.ArmyVOOrBuilder>(
                  armyVOs_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          armyVOs_ = null;
        }
        return armyVOsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:DonateArmyVO)
    }

    static {
      defaultInstance = new DonateArmyVO(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:DonateArmyVO)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_DonateArmyVO_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DonateArmyVO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022DonateArmyVO.proto\032\014ArmyVO.proto\":\n\014Do" +
      "nateArmyVO\022\020\n\010playerid\030\001 \001(\003\022\030\n\007armyVOs\030" +
      "\002 \003(\0132\007.ArmyVOB7\n\037com.pureland.common.pr" +
      "otocal.voB\024DonateArmyVOProtocal"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_DonateArmyVO_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_DonateArmyVO_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_DonateArmyVO_descriptor,
              new java.lang.String[] { "Playerid", "ArmyVOs", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.pureland.common.protocal.vo.ArmyVOProtocal.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
