// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerLoginSimpleVO.proto

package com.pureland.common.protocal.vo;

public final class PlayerLoginSimpleVOProtocal {
  private PlayerLoginSimpleVOProtocal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PlayerLoginSimpleVOOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 userId = 1;
    /**
     * <code>required int64 userId = 1;</code>
     */
    boolean hasUserId();
    /**
     * <code>required int64 userId = 1;</code>
     */
    long getUserId();

    // required int32 raceType = 2;
    /**
     * <code>required int32 raceType = 2;</code>
     */
    boolean hasRaceType();
    /**
     * <code>required int32 raceType = 2;</code>
     */
    int getRaceType();

    // required string userName = 3;
    /**
     * <code>required string userName = 3;</code>
     */
    boolean hasUserName();
    /**
     * <code>required string userName = 3;</code>
     */
    java.lang.String getUserName();
    /**
     * <code>required string userName = 3;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    // required int32 userLevel = 4;
    /**
     * <code>required int32 userLevel = 4;</code>
     */
    boolean hasUserLevel();
    /**
     * <code>required int32 userLevel = 4;</code>
     */
    int getUserLevel();
  }
  /**
   * Protobuf type {@code PlayerLoginSimpleVO}
   */
  public static final class PlayerLoginSimpleVO extends
      com.google.protobuf.GeneratedMessage
      implements PlayerLoginSimpleVOOrBuilder {
    // Use PlayerLoginSimpleVO.newBuilder() to construct.
    private PlayerLoginSimpleVO(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PlayerLoginSimpleVO(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PlayerLoginSimpleVO defaultInstance;
    public static PlayerLoginSimpleVO getDefaultInstance() {
      return defaultInstance;
    }

    public PlayerLoginSimpleVO getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerLoginSimpleVO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              raceType_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              userName_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              userLevel_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pureland.common.protocal.vo.PlayerLoginSimpleVOProtocal.internal_static_PlayerLoginSimpleVO_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pureland.common.protocal.vo.PlayerLoginSimpleVOProtocal.internal_static_PlayerLoginSimpleVO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pureland.common.protocal.vo.PlayerLoginSimpleVOProtocal.PlayerLoginSimpleVO.class, com.pureland.common.protocal.vo.PlayerLoginSimpleVOProtocal.PlayerLoginSimpleVO.Builder.class);
    }

    public static com.google.protobuf.Parser<PlayerLoginSimpleVO> PARSER =
        new com.google.protobuf.AbstractParser<PlayerLoginSimpleVO>() {
      public PlayerLoginSimpleVO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerLoginSimpleVO(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerLoginSimpleVO> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 userId = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private long userId_;
    /**
     * <code>required int64 userId = 1;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 userId = 1;</code>
     */
    public long getUserId() {
      return userId_;
    }

    // required int32 raceType = 2;
    public static final int RACETYPE_FIELD_NUMBER = 2;
    private int raceType_;
    /**
     * <code>required int32 raceType = 2;</code>
     */
    public boolean hasRaceType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 raceType = 2;</code>
     */
    public int getRaceType() {
      return raceType_;
    }

    // required string userName = 3;
    public static final int USERNAME_FIELD_NUMBER = 3;
    private java.lang.Object userName_;
    /**
     * <code>required string userName = 3;</code>
     */
    public boolean hasUserName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string userName = 3;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string userName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 userLevel = 4;
    public static final int USERLEVEL_FIELD_NUMBER = 4;
    private int userLevel_;
    /**
     * <code>required int32 userLevel = 4;</code>
     */
    public boolean hasUserLevel() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 userLevel = 4;</code>
     */
    public int getUserLevel() {
      return userLevel_;
    }

    private void initFields() {
      userId_ = 0L;
      raceType_ = 0;
      userName_ = "";
      userLevel_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRaceType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, raceType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getUserNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, userLevel_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, raceType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getUserNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, userLevel_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.pureland.common.protocal.vo.PlayerLoginSimpleVOProtocal.PlayerLoginSimpleVO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pureland.common.protocal.vo.PlayerLoginSimpleVOProtocal.PlayerLoginSimpleVO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pureland.common.protocal.vo.PlayerLoginSimpleVOProtocal.PlayerLoginSimpleVO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pureland.common.protocal.vo.PlayerLoginSimpleVOProtocal.PlayerLoginSimpleVO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pureland.common.protocal.vo.PlayerLoginSimpleVOProtocal.PlayerLoginSimpleVO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.pureland.common.protocal.vo.PlayerLoginSimpleVOProtocal.PlayerLoginSimpleVO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.pureland.common.protocal.vo.PlayerLoginSimpleVOProtocal.PlayerLoginSimpleVO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.pureland.common.protocal.vo.PlayerLoginSimpleVOProtocal.PlayerLoginSimpleVO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.pureland.common.protocal.vo.PlayerLoginSimpleVOProtocal.PlayerLoginSimpleVO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.pureland.common.protocal.vo.PlayerLoginSimpleVOProtocal.PlayerLoginSimpleVO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.pureland.common.protocal.vo.PlayerLoginSimpleVOProtocal.PlayerLoginSimpleVO prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PlayerLoginSimpleVO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.pureland.common.protocal.vo.PlayerLoginSimpleVOProtocal.PlayerLoginSimpleVOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pureland.common.protocal.vo.PlayerLoginSimpleVOProtocal.internal_static_PlayerLoginSimpleVO_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pureland.common.protocal.vo.PlayerLoginSimpleVOProtocal.internal_static_PlayerLoginSimpleVO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pureland.common.protocal.vo.PlayerLoginSimpleVOProtocal.PlayerLoginSimpleVO.class, com.pureland.common.protocal.vo.PlayerLoginSimpleVOProtocal.PlayerLoginSimpleVO.Builder.class);
      }

      // Construct using com.pureland.common.protocal.vo.PlayerLoginSimpleVOProtocal.PlayerLoginSimpleVO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        raceType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        userName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        userLevel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pureland.common.protocal.vo.PlayerLoginSimpleVOProtocal.internal_static_PlayerLoginSimpleVO_descriptor;
      }

      public com.pureland.common.protocal.vo.PlayerLoginSimpleVOProtocal.PlayerLoginSimpleVO getDefaultInstanceForType() {
        return com.pureland.common.protocal.vo.PlayerLoginSimpleVOProtocal.PlayerLoginSimpleVO.getDefaultInstance();
      }

      public com.pureland.common.protocal.vo.PlayerLoginSimpleVOProtocal.PlayerLoginSimpleVO build() {
        com.pureland.common.protocal.vo.PlayerLoginSimpleVOProtocal.PlayerLoginSimpleVO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.pureland.common.protocal.vo.PlayerLoginSimpleVOProtocal.PlayerLoginSimpleVO buildPartial() {
        com.pureland.common.protocal.vo.PlayerLoginSimpleVOProtocal.PlayerLoginSimpleVO result = new com.pureland.common.protocal.vo.PlayerLoginSimpleVOProtocal.PlayerLoginSimpleVO(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.raceType_ = raceType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.userName_ = userName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.userLevel_ = userLevel_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pureland.common.protocal.vo.PlayerLoginSimpleVOProtocal.PlayerLoginSimpleVO) {
          return mergeFrom((com.pureland.common.protocal.vo.PlayerLoginSimpleVOProtocal.PlayerLoginSimpleVO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.pureland.common.protocal.vo.PlayerLoginSimpleVOProtocal.PlayerLoginSimpleVO other) {
        if (other == com.pureland.common.protocal.vo.PlayerLoginSimpleVOProtocal.PlayerLoginSimpleVO.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasRaceType()) {
          setRaceType(other.getRaceType());
        }
        if (other.hasUserName()) {
          bitField0_ |= 0x00000004;
          userName_ = other.userName_;
          onChanged();
        }
        if (other.hasUserLevel()) {
          setUserLevel(other.getUserLevel());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserId()) {
          
          return false;
        }
        if (!hasRaceType()) {
          
          return false;
        }
        if (!hasUserName()) {
          
          return false;
        }
        if (!hasUserLevel()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.pureland.common.protocal.vo.PlayerLoginSimpleVOProtocal.PlayerLoginSimpleVO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.pureland.common.protocal.vo.PlayerLoginSimpleVOProtocal.PlayerLoginSimpleVO) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 userId = 1;
      private long userId_ ;
      /**
       * <code>required int64 userId = 1;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 userId = 1;</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>required int64 userId = 1;</code>
       */
      public Builder setUserId(long value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 userId = 1;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0L;
        onChanged();
        return this;
      }

      // required int32 raceType = 2;
      private int raceType_ ;
      /**
       * <code>required int32 raceType = 2;</code>
       */
      public boolean hasRaceType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 raceType = 2;</code>
       */
      public int getRaceType() {
        return raceType_;
      }
      /**
       * <code>required int32 raceType = 2;</code>
       */
      public Builder setRaceType(int value) {
        bitField0_ |= 0x00000002;
        raceType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 raceType = 2;</code>
       */
      public Builder clearRaceType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        raceType_ = 0;
        onChanged();
        return this;
      }

      // required string userName = 3;
      private java.lang.Object userName_ = "";
      /**
       * <code>required string userName = 3;</code>
       */
      public boolean hasUserName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string userName = 3;</code>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string userName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string userName = 3;</code>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string userName = 3;</code>
       */
      public Builder clearUserName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>required string userName = 3;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        userName_ = value;
        onChanged();
        return this;
      }

      // required int32 userLevel = 4;
      private int userLevel_ ;
      /**
       * <code>required int32 userLevel = 4;</code>
       */
      public boolean hasUserLevel() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 userLevel = 4;</code>
       */
      public int getUserLevel() {
        return userLevel_;
      }
      /**
       * <code>required int32 userLevel = 4;</code>
       */
      public Builder setUserLevel(int value) {
        bitField0_ |= 0x00000008;
        userLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 userLevel = 4;</code>
       */
      public Builder clearUserLevel() {
        bitField0_ = (bitField0_ & ~0x00000008);
        userLevel_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PlayerLoginSimpleVO)
    }

    static {
      defaultInstance = new PlayerLoginSimpleVO(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PlayerLoginSimpleVO)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerLoginSimpleVO_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PlayerLoginSimpleVO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031PlayerLoginSimpleVO.proto\"\\\n\023PlayerLog" +
      "inSimpleVO\022\016\n\006userId\030\001 \002(\003\022\020\n\010raceType\030\002" +
      " \002(\005\022\020\n\010userName\030\003 \002(\t\022\021\n\tuserLevel\030\004 \002(" +
      "\005B>\n\037com.pureland.common.protocal.voB\033Pl" +
      "ayerLoginSimpleVOProtocal"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_PlayerLoginSimpleVO_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_PlayerLoginSimpleVO_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PlayerLoginSimpleVO_descriptor,
              new java.lang.String[] { "UserId", "RaceType", "UserName", "UserLevel", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
